(define (problem hungrymonkey)
    (:domain M-B-Prob)
    (:objects locale_1 locale_2 locale_3)
    (:init  (location locale_1)
        (location locale_2)
        (location locale_3)
        (at monkey locale_1)
        (on-floor)
        (at chair locale_2)
        (at bananas locale_3)
    )
    (:goal (and (has-all-bananas)))
)