(define (problem monkey_1)
    (:domain monkey-bananas)
  	(:objects p1 p2 p3)
  	(:init 	(location p1) 
		(location p2)
		(location p3)
	 	(at monkey p1)
		(on-floor)
	 	(at chair p2)
	 	(at bananas p3)
	)
  	(:goal (and (hasbananas)))
)