SELECT DISTINCT
    ie.full_name,
    hc.employee_login,
    ie.candidate_id,
    ie.empl_id,
    ie.application_date,
    ie.icims_id,
    ie.ofr_extndd_dt,
    ie.step,
    ie.ofr_accepted_dt,
    ie.loc_cty_nm AS req_loc_cty_nm, 
    ie.loc_bldg_cd AS req_loc_bldg_cd,
    ie.business_title AS req_business_title,
    ie.external_job_title AS req_external_job_title,
    ie.hrng_mngr_reports_to_level3_login, 
    ie.co_nm AS req_co_nm, 
    ie.dept_nm AS req_dept_nm, 
    ie.job_function_desc AS req_job_function_desc,
    ie.job_type, 
    ie.job_level AS req_job_level, 
    ie.rgltry_rgn_cd as req_rgltry_rgn_cd,
    reqs.recruiter_employee_id,
    reqs.recruiter_employee_login,
    reqs.sourcer_employee_id,
    reqs.sourcer_employee_login,
    reqs.snapshot_begin_timestamp,
    reqs.snapshot_end_timestamp,
    ie.clock_stop_time,
    ie.email_address,
    hc.job_title_name as current_job_title, 
    hc.job_level_name as current_job_level,
    hc.location_short_name as  loc_nm,
    ie.reports_to_level3_login, 
    ie.reports_to_suprvsr_login, 
    ie.dept_nm, 
    ie.interview_date, 
    ie.recruiter_login,
    ie.recruiter_nm,
    ie.Business_Lane, 
    ie.team_flag, 
    --interview.interview_summary_id as intrvw_summary_id,
    1 as rnum
    
    FROM opstadw.ops_insearch.irhmd_email ie
    INNER JOIN masterhr.requisition reqs on reqs.job_icims_id = ie.icims_id AND reqs.current_transaction_flag = 'Y'    
    LEFT JOIN masterhr.employee_hc hc on hc.emplid = ie.empl_id AND ie.application_date BETWEEN hc.hr_begin_dt and hc.hr_end_dt
    WHERE 1=1
