(define (problem test_14) 

(:domain sokoban) 

(:objects 
	act_up - action 
	act_down - action 
	act_right - action 
	act_left - action 
	act_teleport - action 
	player_01 - player 
	pos_0_0 - location 
	pos_0_1 - location 
	pos_0_2 - location 
	pos_0_3 - location 
	pos_0_4 - location 
	pos_0_5 - location 
	pos_0_6 - location 
	pos_0_7 - location 
	pos_0_8 - location 
	pos_0_9 - location 
	pos_1_0 - location 
	pos_1_1 - location 
	pos_1_2 - location 
	pos_1_3 - location 
	pos_1_4 - location 
	pos_1_5 - location 
	pos_1_6 - location 
	pos_1_7 - location 
	pos_1_8 - location 
	pos_1_9 - location 
	pos_2_0 - location 
	pos_2_1 - location 
	pos_2_2 - location 
	pos_2_3 - location 
	pos_2_4 - location 
	pos_2_5 - location 
	pos_2_6 - location 
	pos_2_7 - location 
	pos_2_8 - location 
	pos_2_9 - location 
	pos_3_0 - location 
	pos_3_1 - location 
	pos_3_2 - location 
	pos_3_3 - location 
	pos_3_4 - location 
	pos_3_5 - location 
	pos_3_6 - location 
	pos_3_7 - location 
	pos_3_8 - location 
	pos_3_9 - location 
	pos_4_0 - location 
	pos_4_1 - location 
	pos_4_2 - location 
	pos_4_3 - location 
	pos_4_4 - location 
	pos_4_5 - location 
	pos_4_6 - location 
	pos_4_7 - location 
	pos_4_8 - location 
	pos_4_9 - location 
	pos_5_0 - location 
	pos_5_1 - location 
	pos_5_2 - location 
	pos_5_3 - location 
	pos_5_4 - location 
	pos_5_5 - location 
	pos_5_6 - location 
	pos_5_7 - location 
	pos_5_8 - location 
	pos_5_9 - location 
	pos_6_0 - location 
	pos_6_1 - location 
	pos_6_2 - location 
	pos_6_3 - location 
	pos_6_4 - location 
	pos_6_5 - location 
	pos_6_6 - location 
	pos_6_7 - location 
	pos_6_8 - location 
	pos_6_9 - location 
	pos_7_0 - location 
	pos_7_1 - location 
	pos_7_2 - location 
	pos_7_3 - location 
	pos_7_4 - location 
	pos_7_5 - location 
	pos_7_6 - location 
	pos_7_7 - location 
	pos_7_8 - location 
	pos_7_9 - location 
	box_0 - box 
	box_1 - box 
	box_2 - box 
	box_3 - box 
	box_4 - box 
	box_5 - box 
)
(:init 
	(IS-GOAL pos_2_6) 
	(IS-GOAL pos_3_3) 
	(IS-GOAL pos_2_3) 
	(IS-GOAL pos_3_6) 
	(IS-GOAL pos_3_4) 
	(IS-GOAL pos_2_4) 
	(IS-NONGOAL pos_0_0)
	(IS-NONGOAL pos_0_1)
	(IS-NONGOAL pos_0_2)
	(IS-NONGOAL pos_0_3)
	(IS-NONGOAL pos_0_4)
	(IS-NONGOAL pos_0_5)
	(IS-NONGOAL pos_0_6)
	(IS-NONGOAL pos_0_7)
	(IS-NONGOAL pos_0_8)
	(IS-NONGOAL pos_0_9)
	(IS-NONGOAL pos_1_0)
	(IS-NONGOAL pos_1_1)
	(IS-NONGOAL pos_1_2)
	(IS-NONGOAL pos_1_3)
	(IS-NONGOAL pos_1_4)
	(IS-NONGOAL pos_1_5)
	(IS-NONGOAL pos_1_6)
	(IS-NONGOAL pos_1_7)
	(IS-NONGOAL pos_1_8)
	(IS-NONGOAL pos_1_9)
	(IS-NONGOAL pos_2_0)
	(IS-NONGOAL pos_2_1)
	(IS-NONGOAL pos_2_2)
	(IS-NONGOAL pos_2_5)
	(IS-NONGOAL pos_2_7)
	(IS-NONGOAL pos_2_8)
	(IS-NONGOAL pos_2_9)
	(IS-NONGOAL pos_3_0)
	(IS-NONGOAL pos_3_1)
	(IS-NONGOAL pos_3_2)
	(IS-NONGOAL pos_3_5)
	(IS-NONGOAL pos_3_7)
	(IS-NONGOAL pos_3_8)
	(IS-NONGOAL pos_3_9)
	(IS-NONGOAL pos_4_0)
	(IS-NONGOAL pos_4_1)
	(IS-NONGOAL pos_4_2)
	(IS-NONGOAL pos_4_3)
	(IS-NONGOAL pos_4_4)
	(IS-NONGOAL pos_4_5)
	(IS-NONGOAL pos_4_6)
	(IS-NONGOAL pos_4_7)
	(IS-NONGOAL pos_4_8)
	(IS-NONGOAL pos_4_9)
	(IS-NONGOAL pos_5_0)
	(IS-NONGOAL pos_5_1)
	(IS-NONGOAL pos_5_2)
	(IS-NONGOAL pos_5_3)
	(IS-NONGOAL pos_5_4)
	(IS-NONGOAL pos_5_5)
	(IS-NONGOAL pos_5_6)
	(IS-NONGOAL pos_5_7)
	(IS-NONGOAL pos_5_8)
	(IS-NONGOAL pos_5_9)
	(IS-NONGOAL pos_6_0)
	(IS-NONGOAL pos_6_1)
	(IS-NONGOAL pos_6_2)
	(IS-NONGOAL pos_6_3)
	(IS-NONGOAL pos_6_4)
	(IS-NONGOAL pos_6_5)
	(IS-NONGOAL pos_6_6)
	(IS-NONGOAL pos_6_7)
	(IS-NONGOAL pos_6_8)
	(IS-NONGOAL pos_6_9)
	(IS-NONGOAL pos_7_0)
	(IS-NONGOAL pos_7_1)
	(IS-NONGOAL pos_7_2)
	(IS-NONGOAL pos_7_3)
	(IS-NONGOAL pos_7_4)
	(IS-NONGOAL pos_7_5)
	(IS-NONGOAL pos_7_6)
	(IS-NONGOAL pos_7_7)
	(IS-NONGOAL pos_7_8)
	(IS-NONGOAL pos_7_9)
	(at player_01 pos_4_4) 
	(at box_0 pos_3_3) 
	(at box_1 pos_4_6) 
	(at box_2 pos_4_5) 
	(at box_3 pos_2_3) 
	(at box_4 pos_4_3) 
	(at box_5 pos_2_5) 
	(clear pos_0_0)
	(clear pos_0_8)
	(clear pos_0_9)
	(clear pos_1_2)
	(clear pos_1_3)
	(clear pos_1_4)
	(clear pos_1_5)
	(clear pos_1_6)
	(clear pos_1_8)
	(clear pos_2_1)
	(clear pos_2_2)
	(clear pos_2_3)
	(clear pos_2_4)
	(clear pos_2_5)
	(clear pos_2_6)
	(clear pos_2_8)
	(clear pos_2_9)
	(clear pos_3_1)
	(clear pos_3_2)
	(clear pos_3_3)
	(clear pos_3_4)
	(clear pos_3_6)
	(clear pos_4_1)
	(clear pos_4_3)
	(clear pos_4_5)
	(clear pos_4_6)
	(clear pos_4_7)
	(clear pos_4_8)
	(clear pos_5_1)
	(clear pos_5_2)
	(clear pos_5_3)
	(clear pos_5_6)
	(clear pos_5_8)
	(clear pos_6_6)
	(clear pos_6_7)
	(clear pos_6_8)
	(clear pos_7_0)
	(clear pos_7_1)
	(clear pos_7_2)
	(clear pos_7_3)
	(clear pos_7_4)
	(MOVE-DIR pos_4_4 pos_0_0 act_teleport)
	(MOVE-DIR pos_4_4 pos_0_8 act_teleport)
	(MOVE-DIR pos_4_4 pos_0_9 act_teleport)
	(MOVE-DIR pos_4_4 pos_1_2 act_teleport)
	(MOVE-DIR pos_4_4 pos_1_3 act_teleport)
	(MOVE-DIR pos_4_4 pos_1_4 act_teleport)
	(MOVE-DIR pos_4_4 pos_1_5 act_teleport)
	(MOVE-DIR pos_4_4 pos_1_6 act_teleport)
	(MOVE-DIR pos_4_4 pos_1_8 act_teleport)
	(MOVE-DIR pos_4_4 pos_2_1 act_teleport)
	(MOVE-DIR pos_4_4 pos_2_2 act_teleport)
	(MOVE-DIR pos_4_4 pos_2_4 act_teleport)
	(MOVE-DIR pos_4_4 pos_2_6 act_teleport)
	(MOVE-DIR pos_4_4 pos_2_8 act_teleport)
	(MOVE-DIR pos_4_4 pos_2_9 act_teleport)
	(MOVE-DIR pos_4_4 pos_3_1 act_teleport)
	(MOVE-DIR pos_4_4 pos_3_2 act_teleport)
	(MOVE-DIR pos_4_4 pos_3_4 act_teleport)
	(MOVE-DIR pos_4_4 pos_3_6 act_teleport)
	(MOVE-DIR pos_4_4 pos_4_1 act_teleport)
	(MOVE-DIR pos_4_4 pos_4_7 act_teleport)
	(MOVE-DIR pos_4_4 pos_4_8 act_teleport)
	(MOVE-DIR pos_4_4 pos_5_1 act_teleport)
	(MOVE-DIR pos_4_4 pos_5_2 act_teleport)
	(MOVE-DIR pos_4_4 pos_5_3 act_teleport)
	(MOVE-DIR pos_4_4 pos_5_6 act_teleport)
	(MOVE-DIR pos_4_4 pos_5_8 act_teleport)
	(MOVE-DIR pos_4_4 pos_6_6 act_teleport)
	(MOVE-DIR pos_4_4 pos_6_7 act_teleport)
	(MOVE-DIR pos_4_4 pos_6_8 act_teleport)
	(MOVE-DIR pos_4_4 pos_7_0 act_teleport)
	(MOVE-DIR pos_4_4 pos_7_1 act_teleport)
	(MOVE-DIR pos_4_4 pos_7_2 act_teleport)
	(MOVE-DIR pos_4_4 pos_7_3 act_teleport)
	(MOVE-DIR pos_4_4 pos_7_4 act_teleport)
	(MOVE-DIR pos_0_0 pos_4_4 act_teleport)
	(MOVE-DIR pos_0_0 pos_0_8 act_teleport)
	(MOVE-DIR pos_0_0 pos_0_9 act_teleport)
	(MOVE-DIR pos_0_0 pos_1_2 act_teleport)
	(MOVE-DIR pos_0_0 pos_1_3 act_teleport)
	(MOVE-DIR pos_0_0 pos_1_4 act_teleport)
	(MOVE-DIR pos_0_0 pos_1_5 act_teleport)
	(MOVE-DIR pos_0_0 pos_1_6 act_teleport)
	(MOVE-DIR pos_0_0 pos_1_8 act_teleport)
	(MOVE-DIR pos_0_0 pos_2_1 act_teleport)
	(MOVE-DIR pos_0_0 pos_2_2 act_teleport)
	(MOVE-DIR pos_0_0 pos_2_4 act_teleport)
	(MOVE-DIR pos_0_0 pos_2_6 act_teleport)
	(MOVE-DIR pos_0_0 pos_2_8 act_teleport)
	(MOVE-DIR pos_0_0 pos_2_9 act_teleport)
	(MOVE-DIR pos_0_0 pos_3_1 act_teleport)
	(MOVE-DIR pos_0_0 pos_3_2 act_teleport)
	(MOVE-DIR pos_0_0 pos_3_4 act_teleport)
	(MOVE-DIR pos_0_0 pos_3_6 act_teleport)
	(MOVE-DIR pos_0_0 pos_4_1 act_teleport)
	(MOVE-DIR pos_0_0 pos_4_7 act_teleport)
	(MOVE-DIR pos_0_0 pos_4_8 act_teleport)
	(MOVE-DIR pos_0_0 pos_5_1 act_teleport)
	(MOVE-DIR pos_0_0 pos_5_2 act_teleport)
	(MOVE-DIR pos_0_0 pos_5_3 act_teleport)
	(MOVE-DIR pos_0_0 pos_5_6 act_teleport)
	(MOVE-DIR pos_0_0 pos_5_8 act_teleport)
	(MOVE-DIR pos_0_0 pos_6_6 act_teleport)
	(MOVE-DIR pos_0_0 pos_6_7 act_teleport)
	(MOVE-DIR pos_0_0 pos_6_8 act_teleport)
	(MOVE-DIR pos_0_0 pos_7_0 act_teleport)
	(MOVE-DIR pos_0_0 pos_7_1 act_teleport)
	(MOVE-DIR pos_0_0 pos_7_2 act_teleport)
	(MOVE-DIR pos_0_0 pos_7_3 act_teleport)
	(MOVE-DIR pos_0_0 pos_7_4 act_teleport)
	(MOVE-DIR pos_0_8 pos_4_4 act_teleport)
	(MOVE-DIR pos_0_8 pos_0_0 act_teleport)
	(MOVE-DIR pos_0_8 pos_0_9 act_teleport)
	(MOVE-DIR pos_0_8 pos_1_2 act_teleport)
	(MOVE-DIR pos_0_8 pos_1_3 act_teleport)
	(MOVE-DIR pos_0_8 pos_1_4 act_teleport)
	(MOVE-DIR pos_0_8 pos_1_5 act_teleport)
	(MOVE-DIR pos_0_8 pos_1_6 act_teleport)
	(MOVE-DIR pos_0_8 pos_1_8 act_teleport)
	(MOVE-DIR pos_0_8 pos_2_1 act_teleport)
	(MOVE-DIR pos_0_8 pos_2_2 act_teleport)
	(MOVE-DIR pos_0_8 pos_2_4 act_teleport)
	(MOVE-DIR pos_0_8 pos_2_6 act_teleport)
	(MOVE-DIR pos_0_8 pos_2_8 act_teleport)
	(MOVE-DIR pos_0_8 pos_2_9 act_teleport)
	(MOVE-DIR pos_0_8 pos_3_1 act_teleport)
	(MOVE-DIR pos_0_8 pos_3_2 act_teleport)
	(MOVE-DIR pos_0_8 pos_3_4 act_teleport)
	(MOVE-DIR pos_0_8 pos_3_6 act_teleport)
	(MOVE-DIR pos_0_8 pos_4_1 act_teleport)
	(MOVE-DIR pos_0_8 pos_4_7 act_teleport)
	(MOVE-DIR pos_0_8 pos_4_8 act_teleport)
	(MOVE-DIR pos_0_8 pos_5_1 act_teleport)
	(MOVE-DIR pos_0_8 pos_5_2 act_teleport)
	(MOVE-DIR pos_0_8 pos_5_3 act_teleport)
	(MOVE-DIR pos_0_8 pos_5_6 act_teleport)
	(MOVE-DIR pos_0_8 pos_5_8 act_teleport)
	(MOVE-DIR pos_0_8 pos_6_6 act_teleport)
	(MOVE-DIR pos_0_8 pos_6_7 act_teleport)
	(MOVE-DIR pos_0_8 pos_6_8 act_teleport)
	(MOVE-DIR pos_0_8 pos_7_0 act_teleport)
	(MOVE-DIR pos_0_8 pos_7_1 act_teleport)
	(MOVE-DIR pos_0_8 pos_7_2 act_teleport)
	(MOVE-DIR pos_0_8 pos_7_3 act_teleport)
	(MOVE-DIR pos_0_8 pos_7_4 act_teleport)
	(MOVE-DIR pos_0_9 pos_4_4 act_teleport)
	(MOVE-DIR pos_0_9 pos_0_0 act_teleport)
	(MOVE-DIR pos_0_9 pos_0_8 act_teleport)
	(MOVE-DIR pos_0_9 pos_1_2 act_teleport)
	(MOVE-DIR pos_0_9 pos_1_3 act_teleport)
	(MOVE-DIR pos_0_9 pos_1_4 act_teleport)
	(MOVE-DIR pos_0_9 pos_1_5 act_teleport)
	(MOVE-DIR pos_0_9 pos_1_6 act_teleport)
	(MOVE-DIR pos_0_9 pos_1_8 act_teleport)
	(MOVE-DIR pos_0_9 pos_2_1 act_teleport)
	(MOVE-DIR pos_0_9 pos_2_2 act_teleport)
	(MOVE-DIR pos_0_9 pos_2_4 act_teleport)
	(MOVE-DIR pos_0_9 pos_2_6 act_teleport)
	(MOVE-DIR pos_0_9 pos_2_8 act_teleport)
	(MOVE-DIR pos_0_9 pos_2_9 act_teleport)
	(MOVE-DIR pos_0_9 pos_3_1 act_teleport)
	(MOVE-DIR pos_0_9 pos_3_2 act_teleport)
	(MOVE-DIR pos_0_9 pos_3_4 act_teleport)
	(MOVE-DIR pos_0_9 pos_3_6 act_teleport)
	(MOVE-DIR pos_0_9 pos_4_1 act_teleport)
	(MOVE-DIR pos_0_9 pos_4_7 act_teleport)
	(MOVE-DIR pos_0_9 pos_4_8 act_teleport)
	(MOVE-DIR pos_0_9 pos_5_1 act_teleport)
	(MOVE-DIR pos_0_9 pos_5_2 act_teleport)
	(MOVE-DIR pos_0_9 pos_5_3 act_teleport)
	(MOVE-DIR pos_0_9 pos_5_6 act_teleport)
	(MOVE-DIR pos_0_9 pos_5_8 act_teleport)
	(MOVE-DIR pos_0_9 pos_6_6 act_teleport)
	(MOVE-DIR pos_0_9 pos_6_7 act_teleport)
	(MOVE-DIR pos_0_9 pos_6_8 act_teleport)
	(MOVE-DIR pos_0_9 pos_7_0 act_teleport)
	(MOVE-DIR pos_0_9 pos_7_1 act_teleport)
	(MOVE-DIR pos_0_9 pos_7_2 act_teleport)
	(MOVE-DIR pos_0_9 pos_7_3 act_teleport)
	(MOVE-DIR pos_0_9 pos_7_4 act_teleport)
	(MOVE-DIR pos_1_2 pos_4_4 act_teleport)
	(MOVE-DIR pos_1_2 pos_0_0 act_teleport)
	(MOVE-DIR pos_1_2 pos_0_8 act_teleport)
	(MOVE-DIR pos_1_2 pos_0_9 act_teleport)
	(MOVE-DIR pos_1_2 pos_1_3 act_teleport)
	(MOVE-DIR pos_1_2 pos_1_4 act_teleport)
	(MOVE-DIR pos_1_2 pos_1_5 act_teleport)
	(MOVE-DIR pos_1_2 pos_1_6 act_teleport)
	(MOVE-DIR pos_1_2 pos_1_8 act_teleport)
	(MOVE-DIR pos_1_2 pos_2_1 act_teleport)
	(MOVE-DIR pos_1_2 pos_2_2 act_teleport)
	(MOVE-DIR pos_1_2 pos_2_4 act_teleport)
	(MOVE-DIR pos_1_2 pos_2_6 act_teleport)
	(MOVE-DIR pos_1_2 pos_2_8 act_teleport)
	(MOVE-DIR pos_1_2 pos_2_9 act_teleport)
	(MOVE-DIR pos_1_2 pos_3_1 act_teleport)
	(MOVE-DIR pos_1_2 pos_3_2 act_teleport)
	(MOVE-DIR pos_1_2 pos_3_4 act_teleport)
	(MOVE-DIR pos_1_2 pos_3_6 act_teleport)
	(MOVE-DIR pos_1_2 pos_4_1 act_teleport)
	(MOVE-DIR pos_1_2 pos_4_7 act_teleport)
	(MOVE-DIR pos_1_2 pos_4_8 act_teleport)
	(MOVE-DIR pos_1_2 pos_5_1 act_teleport)
	(MOVE-DIR pos_1_2 pos_5_2 act_teleport)
	(MOVE-DIR pos_1_2 pos_5_3 act_teleport)
	(MOVE-DIR pos_1_2 pos_5_6 act_teleport)
	(MOVE-DIR pos_1_2 pos_5_8 act_teleport)
	(MOVE-DIR pos_1_2 pos_6_6 act_teleport)
	(MOVE-DIR pos_1_2 pos_6_7 act_teleport)
	(MOVE-DIR pos_1_2 pos_6_8 act_teleport)
	(MOVE-DIR pos_1_2 pos_7_0 act_teleport)
	(MOVE-DIR pos_1_2 pos_7_1 act_teleport)
	(MOVE-DIR pos_1_2 pos_7_2 act_teleport)
	(MOVE-DIR pos_1_2 pos_7_3 act_teleport)
	(MOVE-DIR pos_1_2 pos_7_4 act_teleport)
	(MOVE-DIR pos_1_3 pos_4_4 act_teleport)
	(MOVE-DIR pos_1_3 pos_0_0 act_teleport)
	(MOVE-DIR pos_1_3 pos_0_8 act_teleport)
	(MOVE-DIR pos_1_3 pos_0_9 act_teleport)
	(MOVE-DIR pos_1_3 pos_1_2 act_teleport)
	(MOVE-DIR pos_1_3 pos_1_4 act_teleport)
	(MOVE-DIR pos_1_3 pos_1_5 act_teleport)
	(MOVE-DIR pos_1_3 pos_1_6 act_teleport)
	(MOVE-DIR pos_1_3 pos_1_8 act_teleport)
	(MOVE-DIR pos_1_3 pos_2_1 act_teleport)
	(MOVE-DIR pos_1_3 pos_2_2 act_teleport)
	(MOVE-DIR pos_1_3 pos_2_4 act_teleport)
	(MOVE-DIR pos_1_3 pos_2_6 act_teleport)
	(MOVE-DIR pos_1_3 pos_2_8 act_teleport)
	(MOVE-DIR pos_1_3 pos_2_9 act_teleport)
	(MOVE-DIR pos_1_3 pos_3_1 act_teleport)
	(MOVE-DIR pos_1_3 pos_3_2 act_teleport)
	(MOVE-DIR pos_1_3 pos_3_4 act_teleport)
	(MOVE-DIR pos_1_3 pos_3_6 act_teleport)
	(MOVE-DIR pos_1_3 pos_4_1 act_teleport)
	(MOVE-DIR pos_1_3 pos_4_7 act_teleport)
	(MOVE-DIR pos_1_3 pos_4_8 act_teleport)
	(MOVE-DIR pos_1_3 pos_5_1 act_teleport)
	(MOVE-DIR pos_1_3 pos_5_2 act_teleport)
	(MOVE-DIR pos_1_3 pos_5_3 act_teleport)
	(MOVE-DIR pos_1_3 pos_5_6 act_teleport)
	(MOVE-DIR pos_1_3 pos_5_8 act_teleport)
	(MOVE-DIR pos_1_3 pos_6_6 act_teleport)
	(MOVE-DIR pos_1_3 pos_6_7 act_teleport)
	(MOVE-DIR pos_1_3 pos_6_8 act_teleport)
	(MOVE-DIR pos_1_3 pos_7_0 act_teleport)
	(MOVE-DIR pos_1_3 pos_7_1 act_teleport)
	(MOVE-DIR pos_1_3 pos_7_2 act_teleport)
	(MOVE-DIR pos_1_3 pos_7_3 act_teleport)
	(MOVE-DIR pos_1_3 pos_7_4 act_teleport)
	(MOVE-DIR pos_1_4 pos_4_4 act_teleport)
	(MOVE-DIR pos_1_4 pos_0_0 act_teleport)
	(MOVE-DIR pos_1_4 pos_0_8 act_teleport)
	(MOVE-DIR pos_1_4 pos_0_9 act_teleport)
	(MOVE-DIR pos_1_4 pos_1_2 act_teleport)
	(MOVE-DIR pos_1_4 pos_1_3 act_teleport)
	(MOVE-DIR pos_1_4 pos_1_5 act_teleport)
	(MOVE-DIR pos_1_4 pos_1_6 act_teleport)
	(MOVE-DIR pos_1_4 pos_1_8 act_teleport)
	(MOVE-DIR pos_1_4 pos_2_1 act_teleport)
	(MOVE-DIR pos_1_4 pos_2_2 act_teleport)
	(MOVE-DIR pos_1_4 pos_2_4 act_teleport)
	(MOVE-DIR pos_1_4 pos_2_6 act_teleport)
	(MOVE-DIR pos_1_4 pos_2_8 act_teleport)
	(MOVE-DIR pos_1_4 pos_2_9 act_teleport)
	(MOVE-DIR pos_1_4 pos_3_1 act_teleport)
	(MOVE-DIR pos_1_4 pos_3_2 act_teleport)
	(MOVE-DIR pos_1_4 pos_3_4 act_teleport)
	(MOVE-DIR pos_1_4 pos_3_6 act_teleport)
	(MOVE-DIR pos_1_4 pos_4_1 act_teleport)
	(MOVE-DIR pos_1_4 pos_4_7 act_teleport)
	(MOVE-DIR pos_1_4 pos_4_8 act_teleport)
	(MOVE-DIR pos_1_4 pos_5_1 act_teleport)
	(MOVE-DIR pos_1_4 pos_5_2 act_teleport)
	(MOVE-DIR pos_1_4 pos_5_3 act_teleport)
	(MOVE-DIR pos_1_4 pos_5_6 act_teleport)
	(MOVE-DIR pos_1_4 pos_5_8 act_teleport)
	(MOVE-DIR pos_1_4 pos_6_6 act_teleport)
	(MOVE-DIR pos_1_4 pos_6_7 act_teleport)
	(MOVE-DIR pos_1_4 pos_6_8 act_teleport)
	(MOVE-DIR pos_1_4 pos_7_0 act_teleport)
	(MOVE-DIR pos_1_4 pos_7_1 act_teleport)
	(MOVE-DIR pos_1_4 pos_7_2 act_teleport)
	(MOVE-DIR pos_1_4 pos_7_3 act_teleport)
	(MOVE-DIR pos_1_4 pos_7_4 act_teleport)
	(MOVE-DIR pos_1_5 pos_4_4 act_teleport)
	(MOVE-DIR pos_1_5 pos_0_0 act_teleport)
	(MOVE-DIR pos_1_5 pos_0_8 act_teleport)
	(MOVE-DIR pos_1_5 pos_0_9 act_teleport)
	(MOVE-DIR pos_1_5 pos_1_2 act_teleport)
	(MOVE-DIR pos_1_5 pos_1_3 act_teleport)
	(MOVE-DIR pos_1_5 pos_1_4 act_teleport)
	(MOVE-DIR pos_1_5 pos_1_6 act_teleport)
	(MOVE-DIR pos_1_5 pos_1_8 act_teleport)
	(MOVE-DIR pos_1_5 pos_2_1 act_teleport)
	(MOVE-DIR pos_1_5 pos_2_2 act_teleport)
	(MOVE-DIR pos_1_5 pos_2_4 act_teleport)
	(MOVE-DIR pos_1_5 pos_2_6 act_teleport)
	(MOVE-DIR pos_1_5 pos_2_8 act_teleport)
	(MOVE-DIR pos_1_5 pos_2_9 act_teleport)
	(MOVE-DIR pos_1_5 pos_3_1 act_teleport)
	(MOVE-DIR pos_1_5 pos_3_2 act_teleport)
	(MOVE-DIR pos_1_5 pos_3_4 act_teleport)
	(MOVE-DIR pos_1_5 pos_3_6 act_teleport)
	(MOVE-DIR pos_1_5 pos_4_1 act_teleport)
	(MOVE-DIR pos_1_5 pos_4_7 act_teleport)
	(MOVE-DIR pos_1_5 pos_4_8 act_teleport)
	(MOVE-DIR pos_1_5 pos_5_1 act_teleport)
	(MOVE-DIR pos_1_5 pos_5_2 act_teleport)
	(MOVE-DIR pos_1_5 pos_5_3 act_teleport)
	(MOVE-DIR pos_1_5 pos_5_6 act_teleport)
	(MOVE-DIR pos_1_5 pos_5_8 act_teleport)
	(MOVE-DIR pos_1_5 pos_6_6 act_teleport)
	(MOVE-DIR pos_1_5 pos_6_7 act_teleport)
	(MOVE-DIR pos_1_5 pos_6_8 act_teleport)
	(MOVE-DIR pos_1_5 pos_7_0 act_teleport)
	(MOVE-DIR pos_1_5 pos_7_1 act_teleport)
	(MOVE-DIR pos_1_5 pos_7_2 act_teleport)
	(MOVE-DIR pos_1_5 pos_7_3 act_teleport)
	(MOVE-DIR pos_1_5 pos_7_4 act_teleport)
	(MOVE-DIR pos_1_6 pos_4_4 act_teleport)
	(MOVE-DIR pos_1_6 pos_0_0 act_teleport)
	(MOVE-DIR pos_1_6 pos_0_8 act_teleport)
	(MOVE-DIR pos_1_6 pos_0_9 act_teleport)
	(MOVE-DIR pos_1_6 pos_1_2 act_teleport)
	(MOVE-DIR pos_1_6 pos_1_3 act_teleport)
	(MOVE-DIR pos_1_6 pos_1_4 act_teleport)
	(MOVE-DIR pos_1_6 pos_1_5 act_teleport)
	(MOVE-DIR pos_1_6 pos_1_8 act_teleport)
	(MOVE-DIR pos_1_6 pos_2_1 act_teleport)
	(MOVE-DIR pos_1_6 pos_2_2 act_teleport)
	(MOVE-DIR pos_1_6 pos_2_4 act_teleport)
	(MOVE-DIR pos_1_6 pos_2_6 act_teleport)
	(MOVE-DIR pos_1_6 pos_2_8 act_teleport)
	(MOVE-DIR pos_1_6 pos_2_9 act_teleport)
	(MOVE-DIR pos_1_6 pos_3_1 act_teleport)
	(MOVE-DIR pos_1_6 pos_3_2 act_teleport)
	(MOVE-DIR pos_1_6 pos_3_4 act_teleport)
	(MOVE-DIR pos_1_6 pos_3_6 act_teleport)
	(MOVE-DIR pos_1_6 pos_4_1 act_teleport)
	(MOVE-DIR pos_1_6 pos_4_7 act_teleport)
	(MOVE-DIR pos_1_6 pos_4_8 act_teleport)
	(MOVE-DIR pos_1_6 pos_5_1 act_teleport)
	(MOVE-DIR pos_1_6 pos_5_2 act_teleport)
	(MOVE-DIR pos_1_6 pos_5_3 act_teleport)
	(MOVE-DIR pos_1_6 pos_5_6 act_teleport)
	(MOVE-DIR pos_1_6 pos_5_8 act_teleport)
	(MOVE-DIR pos_1_6 pos_6_6 act_teleport)
	(MOVE-DIR pos_1_6 pos_6_7 act_teleport)
	(MOVE-DIR pos_1_6 pos_6_8 act_teleport)
	(MOVE-DIR pos_1_6 pos_7_0 act_teleport)
	(MOVE-DIR pos_1_6 pos_7_1 act_teleport)
	(MOVE-DIR pos_1_6 pos_7_2 act_teleport)
	(MOVE-DIR pos_1_6 pos_7_3 act_teleport)
	(MOVE-DIR pos_1_6 pos_7_4 act_teleport)
	(MOVE-DIR pos_1_8 pos_4_4 act_teleport)
	(MOVE-DIR pos_1_8 pos_0_0 act_teleport)
	(MOVE-DIR pos_1_8 pos_0_8 act_teleport)
	(MOVE-DIR pos_1_8 pos_0_9 act_teleport)
	(MOVE-DIR pos_1_8 pos_1_2 act_teleport)
	(MOVE-DIR pos_1_8 pos_1_3 act_teleport)
	(MOVE-DIR pos_1_8 pos_1_4 act_teleport)
	(MOVE-DIR pos_1_8 pos_1_5 act_teleport)
	(MOVE-DIR pos_1_8 pos_1_6 act_teleport)
	(MOVE-DIR pos_1_8 pos_2_1 act_teleport)
	(MOVE-DIR pos_1_8 pos_2_2 act_teleport)
	(MOVE-DIR pos_1_8 pos_2_4 act_teleport)
	(MOVE-DIR pos_1_8 pos_2_6 act_teleport)
	(MOVE-DIR pos_1_8 pos_2_8 act_teleport)
	(MOVE-DIR pos_1_8 pos_2_9 act_teleport)
	(MOVE-DIR pos_1_8 pos_3_1 act_teleport)
	(MOVE-DIR pos_1_8 pos_3_2 act_teleport)
	(MOVE-DIR pos_1_8 pos_3_4 act_teleport)
	(MOVE-DIR pos_1_8 pos_3_6 act_teleport)
	(MOVE-DIR pos_1_8 pos_4_1 act_teleport)
	(MOVE-DIR pos_1_8 pos_4_7 act_teleport)
	(MOVE-DIR pos_1_8 pos_4_8 act_teleport)
	(MOVE-DIR pos_1_8 pos_5_1 act_teleport)
	(MOVE-DIR pos_1_8 pos_5_2 act_teleport)
	(MOVE-DIR pos_1_8 pos_5_3 act_teleport)
	(MOVE-DIR pos_1_8 pos_5_6 act_teleport)
	(MOVE-DIR pos_1_8 pos_5_8 act_teleport)
	(MOVE-DIR pos_1_8 pos_6_6 act_teleport)
	(MOVE-DIR pos_1_8 pos_6_7 act_teleport)
	(MOVE-DIR pos_1_8 pos_6_8 act_teleport)
	(MOVE-DIR pos_1_8 pos_7_0 act_teleport)
	(MOVE-DIR pos_1_8 pos_7_1 act_teleport)
	(MOVE-DIR pos_1_8 pos_7_2 act_teleport)
	(MOVE-DIR pos_1_8 pos_7_3 act_teleport)
	(MOVE-DIR pos_1_8 pos_7_4 act_teleport)
	(MOVE-DIR pos_2_1 pos_4_4 act_teleport)
	(MOVE-DIR pos_2_1 pos_0_0 act_teleport)
	(MOVE-DIR pos_2_1 pos_0_8 act_teleport)
	(MOVE-DIR pos_2_1 pos_0_9 act_teleport)
	(MOVE-DIR pos_2_1 pos_1_2 act_teleport)
	(MOVE-DIR pos_2_1 pos_1_3 act_teleport)
	(MOVE-DIR pos_2_1 pos_1_4 act_teleport)
	(MOVE-DIR pos_2_1 pos_1_5 act_teleport)
	(MOVE-DIR pos_2_1 pos_1_6 act_teleport)
	(MOVE-DIR pos_2_1 pos_1_8 act_teleport)
	(MOVE-DIR pos_2_1 pos_2_2 act_teleport)
	(MOVE-DIR pos_2_1 pos_2_4 act_teleport)
	(MOVE-DIR pos_2_1 pos_2_6 act_teleport)
	(MOVE-DIR pos_2_1 pos_2_8 act_teleport)
	(MOVE-DIR pos_2_1 pos_2_9 act_teleport)
	(MOVE-DIR pos_2_1 pos_3_1 act_teleport)
	(MOVE-DIR pos_2_1 pos_3_2 act_teleport)
	(MOVE-DIR pos_2_1 pos_3_4 act_teleport)
	(MOVE-DIR pos_2_1 pos_3_6 act_teleport)
	(MOVE-DIR pos_2_1 pos_4_1 act_teleport)
	(MOVE-DIR pos_2_1 pos_4_7 act_teleport)
	(MOVE-DIR pos_2_1 pos_4_8 act_teleport)
	(MOVE-DIR pos_2_1 pos_5_1 act_teleport)
	(MOVE-DIR pos_2_1 pos_5_2 act_teleport)
	(MOVE-DIR pos_2_1 pos_5_3 act_teleport)
	(MOVE-DIR pos_2_1 pos_5_6 act_teleport)
	(MOVE-DIR pos_2_1 pos_5_8 act_teleport)
	(MOVE-DIR pos_2_1 pos_6_6 act_teleport)
	(MOVE-DIR pos_2_1 pos_6_7 act_teleport)
	(MOVE-DIR pos_2_1 pos_6_8 act_teleport)
	(MOVE-DIR pos_2_1 pos_7_0 act_teleport)
	(MOVE-DIR pos_2_1 pos_7_1 act_teleport)
	(MOVE-DIR pos_2_1 pos_7_2 act_teleport)
	(MOVE-DIR pos_2_1 pos_7_3 act_teleport)
	(MOVE-DIR pos_2_1 pos_7_4 act_teleport)
	(MOVE-DIR pos_2_2 pos_4_4 act_teleport)
	(MOVE-DIR pos_2_2 pos_0_0 act_teleport)
	(MOVE-DIR pos_2_2 pos_0_8 act_teleport)
	(MOVE-DIR pos_2_2 pos_0_9 act_teleport)
	(MOVE-DIR pos_2_2 pos_1_2 act_teleport)
	(MOVE-DIR pos_2_2 pos_1_3 act_teleport)
	(MOVE-DIR pos_2_2 pos_1_4 act_teleport)
	(MOVE-DIR pos_2_2 pos_1_5 act_teleport)
	(MOVE-DIR pos_2_2 pos_1_6 act_teleport)
	(MOVE-DIR pos_2_2 pos_1_8 act_teleport)
	(MOVE-DIR pos_2_2 pos_2_1 act_teleport)
	(MOVE-DIR pos_2_2 pos_2_4 act_teleport)
	(MOVE-DIR pos_2_2 pos_2_6 act_teleport)
	(MOVE-DIR pos_2_2 pos_2_8 act_teleport)
	(MOVE-DIR pos_2_2 pos_2_9 act_teleport)
	(MOVE-DIR pos_2_2 pos_3_1 act_teleport)
	(MOVE-DIR pos_2_2 pos_3_2 act_teleport)
	(MOVE-DIR pos_2_2 pos_3_4 act_teleport)
	(MOVE-DIR pos_2_2 pos_3_6 act_teleport)
	(MOVE-DIR pos_2_2 pos_4_1 act_teleport)
	(MOVE-DIR pos_2_2 pos_4_7 act_teleport)
	(MOVE-DIR pos_2_2 pos_4_8 act_teleport)
	(MOVE-DIR pos_2_2 pos_5_1 act_teleport)
	(MOVE-DIR pos_2_2 pos_5_2 act_teleport)
	(MOVE-DIR pos_2_2 pos_5_3 act_teleport)
	(MOVE-DIR pos_2_2 pos_5_6 act_teleport)
	(MOVE-DIR pos_2_2 pos_5_8 act_teleport)
	(MOVE-DIR pos_2_2 pos_6_6 act_teleport)
	(MOVE-DIR pos_2_2 pos_6_7 act_teleport)
	(MOVE-DIR pos_2_2 pos_6_8 act_teleport)
	(MOVE-DIR pos_2_2 pos_7_0 act_teleport)
	(MOVE-DIR pos_2_2 pos_7_1 act_teleport)
	(MOVE-DIR pos_2_2 pos_7_2 act_teleport)
	(MOVE-DIR pos_2_2 pos_7_3 act_teleport)
	(MOVE-DIR pos_2_2 pos_7_4 act_teleport)
	(MOVE-DIR pos_2_3 pos_4_4 act_teleport)
	(MOVE-DIR pos_2_3 pos_0_0 act_teleport)
	(MOVE-DIR pos_2_3 pos_0_8 act_teleport)
	(MOVE-DIR pos_2_3 pos_0_9 act_teleport)
	(MOVE-DIR pos_2_3 pos_1_2 act_teleport)
	(MOVE-DIR pos_2_3 pos_1_3 act_teleport)
	(MOVE-DIR pos_2_3 pos_1_4 act_teleport)
	(MOVE-DIR pos_2_3 pos_1_5 act_teleport)
	(MOVE-DIR pos_2_3 pos_1_6 act_teleport)
	(MOVE-DIR pos_2_3 pos_1_8 act_teleport)
	(MOVE-DIR pos_2_3 pos_2_1 act_teleport)
	(MOVE-DIR pos_2_3 pos_2_2 act_teleport)
	(MOVE-DIR pos_2_3 pos_2_4 act_teleport)
	(MOVE-DIR pos_2_3 pos_2_6 act_teleport)
	(MOVE-DIR pos_2_3 pos_2_8 act_teleport)
	(MOVE-DIR pos_2_3 pos_2_9 act_teleport)
	(MOVE-DIR pos_2_3 pos_3_1 act_teleport)
	(MOVE-DIR pos_2_3 pos_3_2 act_teleport)
	(MOVE-DIR pos_2_3 pos_3_4 act_teleport)
	(MOVE-DIR pos_2_3 pos_3_6 act_teleport)
	(MOVE-DIR pos_2_3 pos_4_1 act_teleport)
	(MOVE-DIR pos_2_3 pos_4_7 act_teleport)
	(MOVE-DIR pos_2_3 pos_4_8 act_teleport)
	(MOVE-DIR pos_2_3 pos_5_1 act_teleport)
	(MOVE-DIR pos_2_3 pos_5_2 act_teleport)
	(MOVE-DIR pos_2_3 pos_5_3 act_teleport)
	(MOVE-DIR pos_2_3 pos_5_6 act_teleport)
	(MOVE-DIR pos_2_3 pos_5_8 act_teleport)
	(MOVE-DIR pos_2_3 pos_6_6 act_teleport)
	(MOVE-DIR pos_2_3 pos_6_7 act_teleport)
	(MOVE-DIR pos_2_3 pos_6_8 act_teleport)
	(MOVE-DIR pos_2_3 pos_7_0 act_teleport)
	(MOVE-DIR pos_2_3 pos_7_1 act_teleport)
	(MOVE-DIR pos_2_3 pos_7_2 act_teleport)
	(MOVE-DIR pos_2_3 pos_7_3 act_teleport)
	(MOVE-DIR pos_2_3 pos_7_4 act_teleport)
	(MOVE-DIR pos_2_4 pos_4_4 act_teleport)
	(MOVE-DIR pos_2_4 pos_0_0 act_teleport)
	(MOVE-DIR pos_2_4 pos_0_8 act_teleport)
	(MOVE-DIR pos_2_4 pos_0_9 act_teleport)
	(MOVE-DIR pos_2_4 pos_1_2 act_teleport)
	(MOVE-DIR pos_2_4 pos_1_3 act_teleport)
	(MOVE-DIR pos_2_4 pos_1_4 act_teleport)
	(MOVE-DIR pos_2_4 pos_1_5 act_teleport)
	(MOVE-DIR pos_2_4 pos_1_6 act_teleport)
	(MOVE-DIR pos_2_4 pos_1_8 act_teleport)
	(MOVE-DIR pos_2_4 pos_2_1 act_teleport)
	(MOVE-DIR pos_2_4 pos_2_2 act_teleport)
	(MOVE-DIR pos_2_4 pos_2_6 act_teleport)
	(MOVE-DIR pos_2_4 pos_2_8 act_teleport)
	(MOVE-DIR pos_2_4 pos_2_9 act_teleport)
	(MOVE-DIR pos_2_4 pos_3_1 act_teleport)
	(MOVE-DIR pos_2_4 pos_3_2 act_teleport)
	(MOVE-DIR pos_2_4 pos_3_4 act_teleport)
	(MOVE-DIR pos_2_4 pos_3_6 act_teleport)
	(MOVE-DIR pos_2_4 pos_4_1 act_teleport)
	(MOVE-DIR pos_2_4 pos_4_7 act_teleport)
	(MOVE-DIR pos_2_4 pos_4_8 act_teleport)
	(MOVE-DIR pos_2_4 pos_5_1 act_teleport)
	(MOVE-DIR pos_2_4 pos_5_2 act_teleport)
	(MOVE-DIR pos_2_4 pos_5_3 act_teleport)
	(MOVE-DIR pos_2_4 pos_5_6 act_teleport)
	(MOVE-DIR pos_2_4 pos_5_8 act_teleport)
	(MOVE-DIR pos_2_4 pos_6_6 act_teleport)
	(MOVE-DIR pos_2_4 pos_6_7 act_teleport)
	(MOVE-DIR pos_2_4 pos_6_8 act_teleport)
	(MOVE-DIR pos_2_4 pos_7_0 act_teleport)
	(MOVE-DIR pos_2_4 pos_7_1 act_teleport)
	(MOVE-DIR pos_2_4 pos_7_2 act_teleport)
	(MOVE-DIR pos_2_4 pos_7_3 act_teleport)
	(MOVE-DIR pos_2_4 pos_7_4 act_teleport)
	(MOVE-DIR pos_2_5 pos_4_4 act_teleport)
	(MOVE-DIR pos_2_5 pos_0_0 act_teleport)
	(MOVE-DIR pos_2_5 pos_0_8 act_teleport)
	(MOVE-DIR pos_2_5 pos_0_9 act_teleport)
	(MOVE-DIR pos_2_5 pos_1_2 act_teleport)
	(MOVE-DIR pos_2_5 pos_1_3 act_teleport)
	(MOVE-DIR pos_2_5 pos_1_4 act_teleport)
	(MOVE-DIR pos_2_5 pos_1_5 act_teleport)
	(MOVE-DIR pos_2_5 pos_1_6 act_teleport)
	(MOVE-DIR pos_2_5 pos_1_8 act_teleport)
	(MOVE-DIR pos_2_5 pos_2_1 act_teleport)
	(MOVE-DIR pos_2_5 pos_2_2 act_teleport)
	(MOVE-DIR pos_2_5 pos_2_4 act_teleport)
	(MOVE-DIR pos_2_5 pos_2_6 act_teleport)
	(MOVE-DIR pos_2_5 pos_2_8 act_teleport)
	(MOVE-DIR pos_2_5 pos_2_9 act_teleport)
	(MOVE-DIR pos_2_5 pos_3_1 act_teleport)
	(MOVE-DIR pos_2_5 pos_3_2 act_teleport)
	(MOVE-DIR pos_2_5 pos_3_4 act_teleport)
	(MOVE-DIR pos_2_5 pos_3_6 act_teleport)
	(MOVE-DIR pos_2_5 pos_4_1 act_teleport)
	(MOVE-DIR pos_2_5 pos_4_7 act_teleport)
	(MOVE-DIR pos_2_5 pos_4_8 act_teleport)
	(MOVE-DIR pos_2_5 pos_5_1 act_teleport)
	(MOVE-DIR pos_2_5 pos_5_2 act_teleport)
	(MOVE-DIR pos_2_5 pos_5_3 act_teleport)
	(MOVE-DIR pos_2_5 pos_5_6 act_teleport)
	(MOVE-DIR pos_2_5 pos_5_8 act_teleport)
	(MOVE-DIR pos_2_5 pos_6_6 act_teleport)
	(MOVE-DIR pos_2_5 pos_6_7 act_teleport)
	(MOVE-DIR pos_2_5 pos_6_8 act_teleport)
	(MOVE-DIR pos_2_5 pos_7_0 act_teleport)
	(MOVE-DIR pos_2_5 pos_7_1 act_teleport)
	(MOVE-DIR pos_2_5 pos_7_2 act_teleport)
	(MOVE-DIR pos_2_5 pos_7_3 act_teleport)
	(MOVE-DIR pos_2_5 pos_7_4 act_teleport)
	(MOVE-DIR pos_2_6 pos_4_4 act_teleport)
	(MOVE-DIR pos_2_6 pos_0_0 act_teleport)
	(MOVE-DIR pos_2_6 pos_0_8 act_teleport)
	(MOVE-DIR pos_2_6 pos_0_9 act_teleport)
	(MOVE-DIR pos_2_6 pos_1_2 act_teleport)
	(MOVE-DIR pos_2_6 pos_1_3 act_teleport)
	(MOVE-DIR pos_2_6 pos_1_4 act_teleport)
	(MOVE-DIR pos_2_6 pos_1_5 act_teleport)
	(MOVE-DIR pos_2_6 pos_1_6 act_teleport)
	(MOVE-DIR pos_2_6 pos_1_8 act_teleport)
	(MOVE-DIR pos_2_6 pos_2_1 act_teleport)
	(MOVE-DIR pos_2_6 pos_2_2 act_teleport)
	(MOVE-DIR pos_2_6 pos_2_4 act_teleport)
	(MOVE-DIR pos_2_6 pos_2_8 act_teleport)
	(MOVE-DIR pos_2_6 pos_2_9 act_teleport)
	(MOVE-DIR pos_2_6 pos_3_1 act_teleport)
	(MOVE-DIR pos_2_6 pos_3_2 act_teleport)
	(MOVE-DIR pos_2_6 pos_3_4 act_teleport)
	(MOVE-DIR pos_2_6 pos_3_6 act_teleport)
	(MOVE-DIR pos_2_6 pos_4_1 act_teleport)
	(MOVE-DIR pos_2_6 pos_4_7 act_teleport)
	(MOVE-DIR pos_2_6 pos_4_8 act_teleport)
	(MOVE-DIR pos_2_6 pos_5_1 act_teleport)
	(MOVE-DIR pos_2_6 pos_5_2 act_teleport)
	(MOVE-DIR pos_2_6 pos_5_3 act_teleport)
	(MOVE-DIR pos_2_6 pos_5_6 act_teleport)
	(MOVE-DIR pos_2_6 pos_5_8 act_teleport)
	(MOVE-DIR pos_2_6 pos_6_6 act_teleport)
	(MOVE-DIR pos_2_6 pos_6_7 act_teleport)
	(MOVE-DIR pos_2_6 pos_6_8 act_teleport)
	(MOVE-DIR pos_2_6 pos_7_0 act_teleport)
	(MOVE-DIR pos_2_6 pos_7_1 act_teleport)
	(MOVE-DIR pos_2_6 pos_7_2 act_teleport)
	(MOVE-DIR pos_2_6 pos_7_3 act_teleport)
	(MOVE-DIR pos_2_6 pos_7_4 act_teleport)
	(MOVE-DIR pos_2_8 pos_4_4 act_teleport)
	(MOVE-DIR pos_2_8 pos_0_0 act_teleport)
	(MOVE-DIR pos_2_8 pos_0_8 act_teleport)
	(MOVE-DIR pos_2_8 pos_0_9 act_teleport)
	(MOVE-DIR pos_2_8 pos_1_2 act_teleport)
	(MOVE-DIR pos_2_8 pos_1_3 act_teleport)
	(MOVE-DIR pos_2_8 pos_1_4 act_teleport)
	(MOVE-DIR pos_2_8 pos_1_5 act_teleport)
	(MOVE-DIR pos_2_8 pos_1_6 act_teleport)
	(MOVE-DIR pos_2_8 pos_1_8 act_teleport)
	(MOVE-DIR pos_2_8 pos_2_1 act_teleport)
	(MOVE-DIR pos_2_8 pos_2_2 act_teleport)
	(MOVE-DIR pos_2_8 pos_2_4 act_teleport)
	(MOVE-DIR pos_2_8 pos_2_6 act_teleport)
	(MOVE-DIR pos_2_8 pos_2_9 act_teleport)
	(MOVE-DIR pos_2_8 pos_3_1 act_teleport)
	(MOVE-DIR pos_2_8 pos_3_2 act_teleport)
	(MOVE-DIR pos_2_8 pos_3_4 act_teleport)
	(MOVE-DIR pos_2_8 pos_3_6 act_teleport)
	(MOVE-DIR pos_2_8 pos_4_1 act_teleport)
	(MOVE-DIR pos_2_8 pos_4_7 act_teleport)
	(MOVE-DIR pos_2_8 pos_4_8 act_teleport)
	(MOVE-DIR pos_2_8 pos_5_1 act_teleport)
	(MOVE-DIR pos_2_8 pos_5_2 act_teleport)
	(MOVE-DIR pos_2_8 pos_5_3 act_teleport)
	(MOVE-DIR pos_2_8 pos_5_6 act_teleport)
	(MOVE-DIR pos_2_8 pos_5_8 act_teleport)
	(MOVE-DIR pos_2_8 pos_6_6 act_teleport)
	(MOVE-DIR pos_2_8 pos_6_7 act_teleport)
	(MOVE-DIR pos_2_8 pos_6_8 act_teleport)
	(MOVE-DIR pos_2_8 pos_7_0 act_teleport)
	(MOVE-DIR pos_2_8 pos_7_1 act_teleport)
	(MOVE-DIR pos_2_8 pos_7_2 act_teleport)
	(MOVE-DIR pos_2_8 pos_7_3 act_teleport)
	(MOVE-DIR pos_2_8 pos_7_4 act_teleport)
	(MOVE-DIR pos_2_9 pos_4_4 act_teleport)
	(MOVE-DIR pos_2_9 pos_0_0 act_teleport)
	(MOVE-DIR pos_2_9 pos_0_8 act_teleport)
	(MOVE-DIR pos_2_9 pos_0_9 act_teleport)
	(MOVE-DIR pos_2_9 pos_1_2 act_teleport)
	(MOVE-DIR pos_2_9 pos_1_3 act_teleport)
	(MOVE-DIR pos_2_9 pos_1_4 act_teleport)
	(MOVE-DIR pos_2_9 pos_1_5 act_teleport)
	(MOVE-DIR pos_2_9 pos_1_6 act_teleport)
	(MOVE-DIR pos_2_9 pos_1_8 act_teleport)
	(MOVE-DIR pos_2_9 pos_2_1 act_teleport)
	(MOVE-DIR pos_2_9 pos_2_2 act_teleport)
	(MOVE-DIR pos_2_9 pos_2_4 act_teleport)
	(MOVE-DIR pos_2_9 pos_2_6 act_teleport)
	(MOVE-DIR pos_2_9 pos_2_8 act_teleport)
	(MOVE-DIR pos_2_9 pos_3_1 act_teleport)
	(MOVE-DIR pos_2_9 pos_3_2 act_teleport)
	(MOVE-DIR pos_2_9 pos_3_4 act_teleport)
	(MOVE-DIR pos_2_9 pos_3_6 act_teleport)
	(MOVE-DIR pos_2_9 pos_4_1 act_teleport)
	(MOVE-DIR pos_2_9 pos_4_7 act_teleport)
	(MOVE-DIR pos_2_9 pos_4_8 act_teleport)
	(MOVE-DIR pos_2_9 pos_5_1 act_teleport)
	(MOVE-DIR pos_2_9 pos_5_2 act_teleport)
	(MOVE-DIR pos_2_9 pos_5_3 act_teleport)
	(MOVE-DIR pos_2_9 pos_5_6 act_teleport)
	(MOVE-DIR pos_2_9 pos_5_8 act_teleport)
	(MOVE-DIR pos_2_9 pos_6_6 act_teleport)
	(MOVE-DIR pos_2_9 pos_6_7 act_teleport)
	(MOVE-DIR pos_2_9 pos_6_8 act_teleport)
	(MOVE-DIR pos_2_9 pos_7_0 act_teleport)
	(MOVE-DIR pos_2_9 pos_7_1 act_teleport)
	(MOVE-DIR pos_2_9 pos_7_2 act_teleport)
	(MOVE-DIR pos_2_9 pos_7_3 act_teleport)
	(MOVE-DIR pos_2_9 pos_7_4 act_teleport)
	(MOVE-DIR pos_3_1 pos_4_4 act_teleport)
	(MOVE-DIR pos_3_1 pos_0_0 act_teleport)
	(MOVE-DIR pos_3_1 pos_0_8 act_teleport)
	(MOVE-DIR pos_3_1 pos_0_9 act_teleport)
	(MOVE-DIR pos_3_1 pos_1_2 act_teleport)
	(MOVE-DIR pos_3_1 pos_1_3 act_teleport)
	(MOVE-DIR pos_3_1 pos_1_4 act_teleport)
	(MOVE-DIR pos_3_1 pos_1_5 act_teleport)
	(MOVE-DIR pos_3_1 pos_1_6 act_teleport)
	(MOVE-DIR pos_3_1 pos_1_8 act_teleport)
	(MOVE-DIR pos_3_1 pos_2_1 act_teleport)
	(MOVE-DIR pos_3_1 pos_2_2 act_teleport)
	(MOVE-DIR pos_3_1 pos_2_4 act_teleport)
	(MOVE-DIR pos_3_1 pos_2_6 act_teleport)
	(MOVE-DIR pos_3_1 pos_2_8 act_teleport)
	(MOVE-DIR pos_3_1 pos_2_9 act_teleport)
	(MOVE-DIR pos_3_1 pos_3_2 act_teleport)
	(MOVE-DIR pos_3_1 pos_3_4 act_teleport)
	(MOVE-DIR pos_3_1 pos_3_6 act_teleport)
	(MOVE-DIR pos_3_1 pos_4_1 act_teleport)
	(MOVE-DIR pos_3_1 pos_4_7 act_teleport)
	(MOVE-DIR pos_3_1 pos_4_8 act_teleport)
	(MOVE-DIR pos_3_1 pos_5_1 act_teleport)
	(MOVE-DIR pos_3_1 pos_5_2 act_teleport)
	(MOVE-DIR pos_3_1 pos_5_3 act_teleport)
	(MOVE-DIR pos_3_1 pos_5_6 act_teleport)
	(MOVE-DIR pos_3_1 pos_5_8 act_teleport)
	(MOVE-DIR pos_3_1 pos_6_6 act_teleport)
	(MOVE-DIR pos_3_1 pos_6_7 act_teleport)
	(MOVE-DIR pos_3_1 pos_6_8 act_teleport)
	(MOVE-DIR pos_3_1 pos_7_0 act_teleport)
	(MOVE-DIR pos_3_1 pos_7_1 act_teleport)
	(MOVE-DIR pos_3_1 pos_7_2 act_teleport)
	(MOVE-DIR pos_3_1 pos_7_3 act_teleport)
	(MOVE-DIR pos_3_1 pos_7_4 act_teleport)
	(MOVE-DIR pos_3_2 pos_4_4 act_teleport)
	(MOVE-DIR pos_3_2 pos_0_0 act_teleport)
	(MOVE-DIR pos_3_2 pos_0_8 act_teleport)
	(MOVE-DIR pos_3_2 pos_0_9 act_teleport)
	(MOVE-DIR pos_3_2 pos_1_2 act_teleport)
	(MOVE-DIR pos_3_2 pos_1_3 act_teleport)
	(MOVE-DIR pos_3_2 pos_1_4 act_teleport)
	(MOVE-DIR pos_3_2 pos_1_5 act_teleport)
	(MOVE-DIR pos_3_2 pos_1_6 act_teleport)
	(MOVE-DIR pos_3_2 pos_1_8 act_teleport)
	(MOVE-DIR pos_3_2 pos_2_1 act_teleport)
	(MOVE-DIR pos_3_2 pos_2_2 act_teleport)
	(MOVE-DIR pos_3_2 pos_2_4 act_teleport)
	(MOVE-DIR pos_3_2 pos_2_6 act_teleport)
	(MOVE-DIR pos_3_2 pos_2_8 act_teleport)
	(MOVE-DIR pos_3_2 pos_2_9 act_teleport)
	(MOVE-DIR pos_3_2 pos_3_1 act_teleport)
	(MOVE-DIR pos_3_2 pos_3_4 act_teleport)
	(MOVE-DIR pos_3_2 pos_3_6 act_teleport)
	(MOVE-DIR pos_3_2 pos_4_1 act_teleport)
	(MOVE-DIR pos_3_2 pos_4_7 act_teleport)
	(MOVE-DIR pos_3_2 pos_4_8 act_teleport)
	(MOVE-DIR pos_3_2 pos_5_1 act_teleport)
	(MOVE-DIR pos_3_2 pos_5_2 act_teleport)
	(MOVE-DIR pos_3_2 pos_5_3 act_teleport)
	(MOVE-DIR pos_3_2 pos_5_6 act_teleport)
	(MOVE-DIR pos_3_2 pos_5_8 act_teleport)
	(MOVE-DIR pos_3_2 pos_6_6 act_teleport)
	(MOVE-DIR pos_3_2 pos_6_7 act_teleport)
	(MOVE-DIR pos_3_2 pos_6_8 act_teleport)
	(MOVE-DIR pos_3_2 pos_7_0 act_teleport)
	(MOVE-DIR pos_3_2 pos_7_1 act_teleport)
	(MOVE-DIR pos_3_2 pos_7_2 act_teleport)
	(MOVE-DIR pos_3_2 pos_7_3 act_teleport)
	(MOVE-DIR pos_3_2 pos_7_4 act_teleport)
	(MOVE-DIR pos_3_3 pos_4_4 act_teleport)
	(MOVE-DIR pos_3_3 pos_0_0 act_teleport)
	(MOVE-DIR pos_3_3 pos_0_8 act_teleport)
	(MOVE-DIR pos_3_3 pos_0_9 act_teleport)
	(MOVE-DIR pos_3_3 pos_1_2 act_teleport)
	(MOVE-DIR pos_3_3 pos_1_3 act_teleport)
	(MOVE-DIR pos_3_3 pos_1_4 act_teleport)
	(MOVE-DIR pos_3_3 pos_1_5 act_teleport)
	(MOVE-DIR pos_3_3 pos_1_6 act_teleport)
	(MOVE-DIR pos_3_3 pos_1_8 act_teleport)
	(MOVE-DIR pos_3_3 pos_2_1 act_teleport)
	(MOVE-DIR pos_3_3 pos_2_2 act_teleport)
	(MOVE-DIR pos_3_3 pos_2_4 act_teleport)
	(MOVE-DIR pos_3_3 pos_2_6 act_teleport)
	(MOVE-DIR pos_3_3 pos_2_8 act_teleport)
	(MOVE-DIR pos_3_3 pos_2_9 act_teleport)
	(MOVE-DIR pos_3_3 pos_3_1 act_teleport)
	(MOVE-DIR pos_3_3 pos_3_2 act_teleport)
	(MOVE-DIR pos_3_3 pos_3_4 act_teleport)
	(MOVE-DIR pos_3_3 pos_3_6 act_teleport)
	(MOVE-DIR pos_3_3 pos_4_1 act_teleport)
	(MOVE-DIR pos_3_3 pos_4_7 act_teleport)
	(MOVE-DIR pos_3_3 pos_4_8 act_teleport)
	(MOVE-DIR pos_3_3 pos_5_1 act_teleport)
	(MOVE-DIR pos_3_3 pos_5_2 act_teleport)
	(MOVE-DIR pos_3_3 pos_5_3 act_teleport)
	(MOVE-DIR pos_3_3 pos_5_6 act_teleport)
	(MOVE-DIR pos_3_3 pos_5_8 act_teleport)
	(MOVE-DIR pos_3_3 pos_6_6 act_teleport)
	(MOVE-DIR pos_3_3 pos_6_7 act_teleport)
	(MOVE-DIR pos_3_3 pos_6_8 act_teleport)
	(MOVE-DIR pos_3_3 pos_7_0 act_teleport)
	(MOVE-DIR pos_3_3 pos_7_1 act_teleport)
	(MOVE-DIR pos_3_3 pos_7_2 act_teleport)
	(MOVE-DIR pos_3_3 pos_7_3 act_teleport)
	(MOVE-DIR pos_3_3 pos_7_4 act_teleport)
	(MOVE-DIR pos_3_4 pos_4_4 act_teleport)
	(MOVE-DIR pos_3_4 pos_0_0 act_teleport)
	(MOVE-DIR pos_3_4 pos_0_8 act_teleport)
	(MOVE-DIR pos_3_4 pos_0_9 act_teleport)
	(MOVE-DIR pos_3_4 pos_1_2 act_teleport)
	(MOVE-DIR pos_3_4 pos_1_3 act_teleport)
	(MOVE-DIR pos_3_4 pos_1_4 act_teleport)
	(MOVE-DIR pos_3_4 pos_1_5 act_teleport)
	(MOVE-DIR pos_3_4 pos_1_6 act_teleport)
	(MOVE-DIR pos_3_4 pos_1_8 act_teleport)
	(MOVE-DIR pos_3_4 pos_2_1 act_teleport)
	(MOVE-DIR pos_3_4 pos_2_2 act_teleport)
	(MOVE-DIR pos_3_4 pos_2_4 act_teleport)
	(MOVE-DIR pos_3_4 pos_2_6 act_teleport)
	(MOVE-DIR pos_3_4 pos_2_8 act_teleport)
	(MOVE-DIR pos_3_4 pos_2_9 act_teleport)
	(MOVE-DIR pos_3_4 pos_3_1 act_teleport)
	(MOVE-DIR pos_3_4 pos_3_2 act_teleport)
	(MOVE-DIR pos_3_4 pos_3_6 act_teleport)
	(MOVE-DIR pos_3_4 pos_4_1 act_teleport)
	(MOVE-DIR pos_3_4 pos_4_7 act_teleport)
	(MOVE-DIR pos_3_4 pos_4_8 act_teleport)
	(MOVE-DIR pos_3_4 pos_5_1 act_teleport)
	(MOVE-DIR pos_3_4 pos_5_2 act_teleport)
	(MOVE-DIR pos_3_4 pos_5_3 act_teleport)
	(MOVE-DIR pos_3_4 pos_5_6 act_teleport)
	(MOVE-DIR pos_3_4 pos_5_8 act_teleport)
	(MOVE-DIR pos_3_4 pos_6_6 act_teleport)
	(MOVE-DIR pos_3_4 pos_6_7 act_teleport)
	(MOVE-DIR pos_3_4 pos_6_8 act_teleport)
	(MOVE-DIR pos_3_4 pos_7_0 act_teleport)
	(MOVE-DIR pos_3_4 pos_7_1 act_teleport)
	(MOVE-DIR pos_3_4 pos_7_2 act_teleport)
	(MOVE-DIR pos_3_4 pos_7_3 act_teleport)
	(MOVE-DIR pos_3_4 pos_7_4 act_teleport)
	(MOVE-DIR pos_3_6 pos_4_4 act_teleport)
	(MOVE-DIR pos_3_6 pos_0_0 act_teleport)
	(MOVE-DIR pos_3_6 pos_0_8 act_teleport)
	(MOVE-DIR pos_3_6 pos_0_9 act_teleport)
	(MOVE-DIR pos_3_6 pos_1_2 act_teleport)
	(MOVE-DIR pos_3_6 pos_1_3 act_teleport)
	(MOVE-DIR pos_3_6 pos_1_4 act_teleport)
	(MOVE-DIR pos_3_6 pos_1_5 act_teleport)
	(MOVE-DIR pos_3_6 pos_1_6 act_teleport)
	(MOVE-DIR pos_3_6 pos_1_8 act_teleport)
	(MOVE-DIR pos_3_6 pos_2_1 act_teleport)
	(MOVE-DIR pos_3_6 pos_2_2 act_teleport)
	(MOVE-DIR pos_3_6 pos_2_4 act_teleport)
	(MOVE-DIR pos_3_6 pos_2_6 act_teleport)
	(MOVE-DIR pos_3_6 pos_2_8 act_teleport)
	(MOVE-DIR pos_3_6 pos_2_9 act_teleport)
	(MOVE-DIR pos_3_6 pos_3_1 act_teleport)
	(MOVE-DIR pos_3_6 pos_3_2 act_teleport)
	(MOVE-DIR pos_3_6 pos_3_4 act_teleport)
	(MOVE-DIR pos_3_6 pos_4_1 act_teleport)
	(MOVE-DIR pos_3_6 pos_4_7 act_teleport)
	(MOVE-DIR pos_3_6 pos_4_8 act_teleport)
	(MOVE-DIR pos_3_6 pos_5_1 act_teleport)
	(MOVE-DIR pos_3_6 pos_5_2 act_teleport)
	(MOVE-DIR pos_3_6 pos_5_3 act_teleport)
	(MOVE-DIR pos_3_6 pos_5_6 act_teleport)
	(MOVE-DIR pos_3_6 pos_5_8 act_teleport)
	(MOVE-DIR pos_3_6 pos_6_6 act_teleport)
	(MOVE-DIR pos_3_6 pos_6_7 act_teleport)
	(MOVE-DIR pos_3_6 pos_6_8 act_teleport)
	(MOVE-DIR pos_3_6 pos_7_0 act_teleport)
	(MOVE-DIR pos_3_6 pos_7_1 act_teleport)
	(MOVE-DIR pos_3_6 pos_7_2 act_teleport)
	(MOVE-DIR pos_3_6 pos_7_3 act_teleport)
	(MOVE-DIR pos_3_6 pos_7_4 act_teleport)
	(MOVE-DIR pos_4_1 pos_4_4 act_teleport)
	(MOVE-DIR pos_4_1 pos_0_0 act_teleport)
	(MOVE-DIR pos_4_1 pos_0_8 act_teleport)
	(MOVE-DIR pos_4_1 pos_0_9 act_teleport)
	(MOVE-DIR pos_4_1 pos_1_2 act_teleport)
	(MOVE-DIR pos_4_1 pos_1_3 act_teleport)
	(MOVE-DIR pos_4_1 pos_1_4 act_teleport)
	(MOVE-DIR pos_4_1 pos_1_5 act_teleport)
	(MOVE-DIR pos_4_1 pos_1_6 act_teleport)
	(MOVE-DIR pos_4_1 pos_1_8 act_teleport)
	(MOVE-DIR pos_4_1 pos_2_1 act_teleport)
	(MOVE-DIR pos_4_1 pos_2_2 act_teleport)
	(MOVE-DIR pos_4_1 pos_2_4 act_teleport)
	(MOVE-DIR pos_4_1 pos_2_6 act_teleport)
	(MOVE-DIR pos_4_1 pos_2_8 act_teleport)
	(MOVE-DIR pos_4_1 pos_2_9 act_teleport)
	(MOVE-DIR pos_4_1 pos_3_1 act_teleport)
	(MOVE-DIR pos_4_1 pos_3_2 act_teleport)
	(MOVE-DIR pos_4_1 pos_3_4 act_teleport)
	(MOVE-DIR pos_4_1 pos_3_6 act_teleport)
	(MOVE-DIR pos_4_1 pos_4_7 act_teleport)
	(MOVE-DIR pos_4_1 pos_4_8 act_teleport)
	(MOVE-DIR pos_4_1 pos_5_1 act_teleport)
	(MOVE-DIR pos_4_1 pos_5_2 act_teleport)
	(MOVE-DIR pos_4_1 pos_5_3 act_teleport)
	(MOVE-DIR pos_4_1 pos_5_6 act_teleport)
	(MOVE-DIR pos_4_1 pos_5_8 act_teleport)
	(MOVE-DIR pos_4_1 pos_6_6 act_teleport)
	(MOVE-DIR pos_4_1 pos_6_7 act_teleport)
	(MOVE-DIR pos_4_1 pos_6_8 act_teleport)
	(MOVE-DIR pos_4_1 pos_7_0 act_teleport)
	(MOVE-DIR pos_4_1 pos_7_1 act_teleport)
	(MOVE-DIR pos_4_1 pos_7_2 act_teleport)
	(MOVE-DIR pos_4_1 pos_7_3 act_teleport)
	(MOVE-DIR pos_4_1 pos_7_4 act_teleport)
	(MOVE-DIR pos_4_3 pos_4_4 act_teleport)
	(MOVE-DIR pos_4_3 pos_0_0 act_teleport)
	(MOVE-DIR pos_4_3 pos_0_8 act_teleport)
	(MOVE-DIR pos_4_3 pos_0_9 act_teleport)
	(MOVE-DIR pos_4_3 pos_1_2 act_teleport)
	(MOVE-DIR pos_4_3 pos_1_3 act_teleport)
	(MOVE-DIR pos_4_3 pos_1_4 act_teleport)
	(MOVE-DIR pos_4_3 pos_1_5 act_teleport)
	(MOVE-DIR pos_4_3 pos_1_6 act_teleport)
	(MOVE-DIR pos_4_3 pos_1_8 act_teleport)
	(MOVE-DIR pos_4_3 pos_2_1 act_teleport)
	(MOVE-DIR pos_4_3 pos_2_2 act_teleport)
	(MOVE-DIR pos_4_3 pos_2_4 act_teleport)
	(MOVE-DIR pos_4_3 pos_2_6 act_teleport)
	(MOVE-DIR pos_4_3 pos_2_8 act_teleport)
	(MOVE-DIR pos_4_3 pos_2_9 act_teleport)
	(MOVE-DIR pos_4_3 pos_3_1 act_teleport)
	(MOVE-DIR pos_4_3 pos_3_2 act_teleport)
	(MOVE-DIR pos_4_3 pos_3_4 act_teleport)
	(MOVE-DIR pos_4_3 pos_3_6 act_teleport)
	(MOVE-DIR pos_4_3 pos_4_1 act_teleport)
	(MOVE-DIR pos_4_3 pos_4_7 act_teleport)
	(MOVE-DIR pos_4_3 pos_4_8 act_teleport)
	(MOVE-DIR pos_4_3 pos_5_1 act_teleport)
	(MOVE-DIR pos_4_3 pos_5_2 act_teleport)
	(MOVE-DIR pos_4_3 pos_5_3 act_teleport)
	(MOVE-DIR pos_4_3 pos_5_6 act_teleport)
	(MOVE-DIR pos_4_3 pos_5_8 act_teleport)
	(MOVE-DIR pos_4_3 pos_6_6 act_teleport)
	(MOVE-DIR pos_4_3 pos_6_7 act_teleport)
	(MOVE-DIR pos_4_3 pos_6_8 act_teleport)
	(MOVE-DIR pos_4_3 pos_7_0 act_teleport)
	(MOVE-DIR pos_4_3 pos_7_1 act_teleport)
	(MOVE-DIR pos_4_3 pos_7_2 act_teleport)
	(MOVE-DIR pos_4_3 pos_7_3 act_teleport)
	(MOVE-DIR pos_4_3 pos_7_4 act_teleport)
	(MOVE-DIR pos_4_5 pos_4_4 act_teleport)
	(MOVE-DIR pos_4_5 pos_0_0 act_teleport)
	(MOVE-DIR pos_4_5 pos_0_8 act_teleport)
	(MOVE-DIR pos_4_5 pos_0_9 act_teleport)
	(MOVE-DIR pos_4_5 pos_1_2 act_teleport)
	(MOVE-DIR pos_4_5 pos_1_3 act_teleport)
	(MOVE-DIR pos_4_5 pos_1_4 act_teleport)
	(MOVE-DIR pos_4_5 pos_1_5 act_teleport)
	(MOVE-DIR pos_4_5 pos_1_6 act_teleport)
	(MOVE-DIR pos_4_5 pos_1_8 act_teleport)
	(MOVE-DIR pos_4_5 pos_2_1 act_teleport)
	(MOVE-DIR pos_4_5 pos_2_2 act_teleport)
	(MOVE-DIR pos_4_5 pos_2_4 act_teleport)
	(MOVE-DIR pos_4_5 pos_2_6 act_teleport)
	(MOVE-DIR pos_4_5 pos_2_8 act_teleport)
	(MOVE-DIR pos_4_5 pos_2_9 act_teleport)
	(MOVE-DIR pos_4_5 pos_3_1 act_teleport)
	(MOVE-DIR pos_4_5 pos_3_2 act_teleport)
	(MOVE-DIR pos_4_5 pos_3_4 act_teleport)
	(MOVE-DIR pos_4_5 pos_3_6 act_teleport)
	(MOVE-DIR pos_4_5 pos_4_1 act_teleport)
	(MOVE-DIR pos_4_5 pos_4_7 act_teleport)
	(MOVE-DIR pos_4_5 pos_4_8 act_teleport)
	(MOVE-DIR pos_4_5 pos_5_1 act_teleport)
	(MOVE-DIR pos_4_5 pos_5_2 act_teleport)
	(MOVE-DIR pos_4_5 pos_5_3 act_teleport)
	(MOVE-DIR pos_4_5 pos_5_6 act_teleport)
	(MOVE-DIR pos_4_5 pos_5_8 act_teleport)
	(MOVE-DIR pos_4_5 pos_6_6 act_teleport)
	(MOVE-DIR pos_4_5 pos_6_7 act_teleport)
	(MOVE-DIR pos_4_5 pos_6_8 act_teleport)
	(MOVE-DIR pos_4_5 pos_7_0 act_teleport)
	(MOVE-DIR pos_4_5 pos_7_1 act_teleport)
	(MOVE-DIR pos_4_5 pos_7_2 act_teleport)
	(MOVE-DIR pos_4_5 pos_7_3 act_teleport)
	(MOVE-DIR pos_4_5 pos_7_4 act_teleport)
	(MOVE-DIR pos_4_6 pos_4_4 act_teleport)
	(MOVE-DIR pos_4_6 pos_0_0 act_teleport)
	(MOVE-DIR pos_4_6 pos_0_8 act_teleport)
	(MOVE-DIR pos_4_6 pos_0_9 act_teleport)
	(MOVE-DIR pos_4_6 pos_1_2 act_teleport)
	(MOVE-DIR pos_4_6 pos_1_3 act_teleport)
	(MOVE-DIR pos_4_6 pos_1_4 act_teleport)
	(MOVE-DIR pos_4_6 pos_1_5 act_teleport)
	(MOVE-DIR pos_4_6 pos_1_6 act_teleport)
	(MOVE-DIR pos_4_6 pos_1_8 act_teleport)
	(MOVE-DIR pos_4_6 pos_2_1 act_teleport)
	(MOVE-DIR pos_4_6 pos_2_2 act_teleport)
	(MOVE-DIR pos_4_6 pos_2_4 act_teleport)
	(MOVE-DIR pos_4_6 pos_2_6 act_teleport)
	(MOVE-DIR pos_4_6 pos_2_8 act_teleport)
	(MOVE-DIR pos_4_6 pos_2_9 act_teleport)
	(MOVE-DIR pos_4_6 pos_3_1 act_teleport)
	(MOVE-DIR pos_4_6 pos_3_2 act_teleport)
	(MOVE-DIR pos_4_6 pos_3_4 act_teleport)
	(MOVE-DIR pos_4_6 pos_3_6 act_teleport)
	(MOVE-DIR pos_4_6 pos_4_1 act_teleport)
	(MOVE-DIR pos_4_6 pos_4_7 act_teleport)
	(MOVE-DIR pos_4_6 pos_4_8 act_teleport)
	(MOVE-DIR pos_4_6 pos_5_1 act_teleport)
	(MOVE-DIR pos_4_6 pos_5_2 act_teleport)
	(MOVE-DIR pos_4_6 pos_5_3 act_teleport)
	(MOVE-DIR pos_4_6 pos_5_6 act_teleport)
	(MOVE-DIR pos_4_6 pos_5_8 act_teleport)
	(MOVE-DIR pos_4_6 pos_6_6 act_teleport)
	(MOVE-DIR pos_4_6 pos_6_7 act_teleport)
	(MOVE-DIR pos_4_6 pos_6_8 act_teleport)
	(MOVE-DIR pos_4_6 pos_7_0 act_teleport)
	(MOVE-DIR pos_4_6 pos_7_1 act_teleport)
	(MOVE-DIR pos_4_6 pos_7_2 act_teleport)
	(MOVE-DIR pos_4_6 pos_7_3 act_teleport)
	(MOVE-DIR pos_4_6 pos_7_4 act_teleport)
	(MOVE-DIR pos_4_7 pos_4_4 act_teleport)
	(MOVE-DIR pos_4_7 pos_0_0 act_teleport)
	(MOVE-DIR pos_4_7 pos_0_8 act_teleport)
	(MOVE-DIR pos_4_7 pos_0_9 act_teleport)
	(MOVE-DIR pos_4_7 pos_1_2 act_teleport)
	(MOVE-DIR pos_4_7 pos_1_3 act_teleport)
	(MOVE-DIR pos_4_7 pos_1_4 act_teleport)
	(MOVE-DIR pos_4_7 pos_1_5 act_teleport)
	(MOVE-DIR pos_4_7 pos_1_6 act_teleport)
	(MOVE-DIR pos_4_7 pos_1_8 act_teleport)
	(MOVE-DIR pos_4_7 pos_2_1 act_teleport)
	(MOVE-DIR pos_4_7 pos_2_2 act_teleport)
	(MOVE-DIR pos_4_7 pos_2_4 act_teleport)
	(MOVE-DIR pos_4_7 pos_2_6 act_teleport)
	(MOVE-DIR pos_4_7 pos_2_8 act_teleport)
	(MOVE-DIR pos_4_7 pos_2_9 act_teleport)
	(MOVE-DIR pos_4_7 pos_3_1 act_teleport)
	(MOVE-DIR pos_4_7 pos_3_2 act_teleport)
	(MOVE-DIR pos_4_7 pos_3_4 act_teleport)
	(MOVE-DIR pos_4_7 pos_3_6 act_teleport)
	(MOVE-DIR pos_4_7 pos_4_1 act_teleport)
	(MOVE-DIR pos_4_7 pos_4_8 act_teleport)
	(MOVE-DIR pos_4_7 pos_5_1 act_teleport)
	(MOVE-DIR pos_4_7 pos_5_2 act_teleport)
	(MOVE-DIR pos_4_7 pos_5_3 act_teleport)
	(MOVE-DIR pos_4_7 pos_5_6 act_teleport)
	(MOVE-DIR pos_4_7 pos_5_8 act_teleport)
	(MOVE-DIR pos_4_7 pos_6_6 act_teleport)
	(MOVE-DIR pos_4_7 pos_6_7 act_teleport)
	(MOVE-DIR pos_4_7 pos_6_8 act_teleport)
	(MOVE-DIR pos_4_7 pos_7_0 act_teleport)
	(MOVE-DIR pos_4_7 pos_7_1 act_teleport)
	(MOVE-DIR pos_4_7 pos_7_2 act_teleport)
	(MOVE-DIR pos_4_7 pos_7_3 act_teleport)
	(MOVE-DIR pos_4_7 pos_7_4 act_teleport)
	(MOVE-DIR pos_4_8 pos_4_4 act_teleport)
	(MOVE-DIR pos_4_8 pos_0_0 act_teleport)
	(MOVE-DIR pos_4_8 pos_0_8 act_teleport)
	(MOVE-DIR pos_4_8 pos_0_9 act_teleport)
	(MOVE-DIR pos_4_8 pos_1_2 act_teleport)
	(MOVE-DIR pos_4_8 pos_1_3 act_teleport)
	(MOVE-DIR pos_4_8 pos_1_4 act_teleport)
	(MOVE-DIR pos_4_8 pos_1_5 act_teleport)
	(MOVE-DIR pos_4_8 pos_1_6 act_teleport)
	(MOVE-DIR pos_4_8 pos_1_8 act_teleport)
	(MOVE-DIR pos_4_8 pos_2_1 act_teleport)
	(MOVE-DIR pos_4_8 pos_2_2 act_teleport)
	(MOVE-DIR pos_4_8 pos_2_4 act_teleport)
	(MOVE-DIR pos_4_8 pos_2_6 act_teleport)
	(MOVE-DIR pos_4_8 pos_2_8 act_teleport)
	(MOVE-DIR pos_4_8 pos_2_9 act_teleport)
	(MOVE-DIR pos_4_8 pos_3_1 act_teleport)
	(MOVE-DIR pos_4_8 pos_3_2 act_teleport)
	(MOVE-DIR pos_4_8 pos_3_4 act_teleport)
	(MOVE-DIR pos_4_8 pos_3_6 act_teleport)
	(MOVE-DIR pos_4_8 pos_4_1 act_teleport)
	(MOVE-DIR pos_4_8 pos_4_7 act_teleport)
	(MOVE-DIR pos_4_8 pos_5_1 act_teleport)
	(MOVE-DIR pos_4_8 pos_5_2 act_teleport)
	(MOVE-DIR pos_4_8 pos_5_3 act_teleport)
	(MOVE-DIR pos_4_8 pos_5_6 act_teleport)
	(MOVE-DIR pos_4_8 pos_5_8 act_teleport)
	(MOVE-DIR pos_4_8 pos_6_6 act_teleport)
	(MOVE-DIR pos_4_8 pos_6_7 act_teleport)
	(MOVE-DIR pos_4_8 pos_6_8 act_teleport)
	(MOVE-DIR pos_4_8 pos_7_0 act_teleport)
	(MOVE-DIR pos_4_8 pos_7_1 act_teleport)
	(MOVE-DIR pos_4_8 pos_7_2 act_teleport)
	(MOVE-DIR pos_4_8 pos_7_3 act_teleport)
	(MOVE-DIR pos_4_8 pos_7_4 act_teleport)
	(MOVE-DIR pos_5_1 pos_4_4 act_teleport)
	(MOVE-DIR pos_5_1 pos_0_0 act_teleport)
	(MOVE-DIR pos_5_1 pos_0_8 act_teleport)
	(MOVE-DIR pos_5_1 pos_0_9 act_teleport)
	(MOVE-DIR pos_5_1 pos_1_2 act_teleport)
	(MOVE-DIR pos_5_1 pos_1_3 act_teleport)
	(MOVE-DIR pos_5_1 pos_1_4 act_teleport)
	(MOVE-DIR pos_5_1 pos_1_5 act_teleport)
	(MOVE-DIR pos_5_1 pos_1_6 act_teleport)
	(MOVE-DIR pos_5_1 pos_1_8 act_teleport)
	(MOVE-DIR pos_5_1 pos_2_1 act_teleport)
	(MOVE-DIR pos_5_1 pos_2_2 act_teleport)
	(MOVE-DIR pos_5_1 pos_2_4 act_teleport)
	(MOVE-DIR pos_5_1 pos_2_6 act_teleport)
	(MOVE-DIR pos_5_1 pos_2_8 act_teleport)
	(MOVE-DIR pos_5_1 pos_2_9 act_teleport)
	(MOVE-DIR pos_5_1 pos_3_1 act_teleport)
	(MOVE-DIR pos_5_1 pos_3_2 act_teleport)
	(MOVE-DIR pos_5_1 pos_3_4 act_teleport)
	(MOVE-DIR pos_5_1 pos_3_6 act_teleport)
	(MOVE-DIR pos_5_1 pos_4_1 act_teleport)
	(MOVE-DIR pos_5_1 pos_4_7 act_teleport)
	(MOVE-DIR pos_5_1 pos_4_8 act_teleport)
	(MOVE-DIR pos_5_1 pos_5_2 act_teleport)
	(MOVE-DIR pos_5_1 pos_5_3 act_teleport)
	(MOVE-DIR pos_5_1 pos_5_6 act_teleport)
	(MOVE-DIR pos_5_1 pos_5_8 act_teleport)
	(MOVE-DIR pos_5_1 pos_6_6 act_teleport)
	(MOVE-DIR pos_5_1 pos_6_7 act_teleport)
	(MOVE-DIR pos_5_1 pos_6_8 act_teleport)
	(MOVE-DIR pos_5_1 pos_7_0 act_teleport)
	(MOVE-DIR pos_5_1 pos_7_1 act_teleport)
	(MOVE-DIR pos_5_1 pos_7_2 act_teleport)
	(MOVE-DIR pos_5_1 pos_7_3 act_teleport)
	(MOVE-DIR pos_5_1 pos_7_4 act_teleport)
	(MOVE-DIR pos_5_2 pos_4_4 act_teleport)
	(MOVE-DIR pos_5_2 pos_0_0 act_teleport)
	(MOVE-DIR pos_5_2 pos_0_8 act_teleport)
	(MOVE-DIR pos_5_2 pos_0_9 act_teleport)
	(MOVE-DIR pos_5_2 pos_1_2 act_teleport)
	(MOVE-DIR pos_5_2 pos_1_3 act_teleport)
	(MOVE-DIR pos_5_2 pos_1_4 act_teleport)
	(MOVE-DIR pos_5_2 pos_1_5 act_teleport)
	(MOVE-DIR pos_5_2 pos_1_6 act_teleport)
	(MOVE-DIR pos_5_2 pos_1_8 act_teleport)
	(MOVE-DIR pos_5_2 pos_2_1 act_teleport)
	(MOVE-DIR pos_5_2 pos_2_2 act_teleport)
	(MOVE-DIR pos_5_2 pos_2_4 act_teleport)
	(MOVE-DIR pos_5_2 pos_2_6 act_teleport)
	(MOVE-DIR pos_5_2 pos_2_8 act_teleport)
	(MOVE-DIR pos_5_2 pos_2_9 act_teleport)
	(MOVE-DIR pos_5_2 pos_3_1 act_teleport)
	(MOVE-DIR pos_5_2 pos_3_2 act_teleport)
	(MOVE-DIR pos_5_2 pos_3_4 act_teleport)
	(MOVE-DIR pos_5_2 pos_3_6 act_teleport)
	(MOVE-DIR pos_5_2 pos_4_1 act_teleport)
	(MOVE-DIR pos_5_2 pos_4_7 act_teleport)
	(MOVE-DIR pos_5_2 pos_4_8 act_teleport)
	(MOVE-DIR pos_5_2 pos_5_1 act_teleport)
	(MOVE-DIR pos_5_2 pos_5_3 act_teleport)
	(MOVE-DIR pos_5_2 pos_5_6 act_teleport)
	(MOVE-DIR pos_5_2 pos_5_8 act_teleport)
	(MOVE-DIR pos_5_2 pos_6_6 act_teleport)
	(MOVE-DIR pos_5_2 pos_6_7 act_teleport)
	(MOVE-DIR pos_5_2 pos_6_8 act_teleport)
	(MOVE-DIR pos_5_2 pos_7_0 act_teleport)
	(MOVE-DIR pos_5_2 pos_7_1 act_teleport)
	(MOVE-DIR pos_5_2 pos_7_2 act_teleport)
	(MOVE-DIR pos_5_2 pos_7_3 act_teleport)
	(MOVE-DIR pos_5_2 pos_7_4 act_teleport)
	(MOVE-DIR pos_5_3 pos_4_4 act_teleport)
	(MOVE-DIR pos_5_3 pos_0_0 act_teleport)
	(MOVE-DIR pos_5_3 pos_0_8 act_teleport)
	(MOVE-DIR pos_5_3 pos_0_9 act_teleport)
	(MOVE-DIR pos_5_3 pos_1_2 act_teleport)
	(MOVE-DIR pos_5_3 pos_1_3 act_teleport)
	(MOVE-DIR pos_5_3 pos_1_4 act_teleport)
	(MOVE-DIR pos_5_3 pos_1_5 act_teleport)
	(MOVE-DIR pos_5_3 pos_1_6 act_teleport)
	(MOVE-DIR pos_5_3 pos_1_8 act_teleport)
	(MOVE-DIR pos_5_3 pos_2_1 act_teleport)
	(MOVE-DIR pos_5_3 pos_2_2 act_teleport)
	(MOVE-DIR pos_5_3 pos_2_4 act_teleport)
	(MOVE-DIR pos_5_3 pos_2_6 act_teleport)
	(MOVE-DIR pos_5_3 pos_2_8 act_teleport)
	(MOVE-DIR pos_5_3 pos_2_9 act_teleport)
	(MOVE-DIR pos_5_3 pos_3_1 act_teleport)
	(MOVE-DIR pos_5_3 pos_3_2 act_teleport)
	(MOVE-DIR pos_5_3 pos_3_4 act_teleport)
	(MOVE-DIR pos_5_3 pos_3_6 act_teleport)
	(MOVE-DIR pos_5_3 pos_4_1 act_teleport)
	(MOVE-DIR pos_5_3 pos_4_7 act_teleport)
	(MOVE-DIR pos_5_3 pos_4_8 act_teleport)
	(MOVE-DIR pos_5_3 pos_5_1 act_teleport)
	(MOVE-DIR pos_5_3 pos_5_2 act_teleport)
	(MOVE-DIR pos_5_3 pos_5_6 act_teleport)
	(MOVE-DIR pos_5_3 pos_5_8 act_teleport)
	(MOVE-DIR pos_5_3 pos_6_6 act_teleport)
	(MOVE-DIR pos_5_3 pos_6_7 act_teleport)
	(MOVE-DIR pos_5_3 pos_6_8 act_teleport)
	(MOVE-DIR pos_5_3 pos_7_0 act_teleport)
	(MOVE-DIR pos_5_3 pos_7_1 act_teleport)
	(MOVE-DIR pos_5_3 pos_7_2 act_teleport)
	(MOVE-DIR pos_5_3 pos_7_3 act_teleport)
	(MOVE-DIR pos_5_3 pos_7_4 act_teleport)
	(MOVE-DIR pos_5_6 pos_4_4 act_teleport)
	(MOVE-DIR pos_5_6 pos_0_0 act_teleport)
	(MOVE-DIR pos_5_6 pos_0_8 act_teleport)
	(MOVE-DIR pos_5_6 pos_0_9 act_teleport)
	(MOVE-DIR pos_5_6 pos_1_2 act_teleport)
	(MOVE-DIR pos_5_6 pos_1_3 act_teleport)
	(MOVE-DIR pos_5_6 pos_1_4 act_teleport)
	(MOVE-DIR pos_5_6 pos_1_5 act_teleport)
	(MOVE-DIR pos_5_6 pos_1_6 act_teleport)
	(MOVE-DIR pos_5_6 pos_1_8 act_teleport)
	(MOVE-DIR pos_5_6 pos_2_1 act_teleport)
	(MOVE-DIR pos_5_6 pos_2_2 act_teleport)
	(MOVE-DIR pos_5_6 pos_2_4 act_teleport)
	(MOVE-DIR pos_5_6 pos_2_6 act_teleport)
	(MOVE-DIR pos_5_6 pos_2_8 act_teleport)
	(MOVE-DIR pos_5_6 pos_2_9 act_teleport)
	(MOVE-DIR pos_5_6 pos_3_1 act_teleport)
	(MOVE-DIR pos_5_6 pos_3_2 act_teleport)
	(MOVE-DIR pos_5_6 pos_3_4 act_teleport)
	(MOVE-DIR pos_5_6 pos_3_6 act_teleport)
	(MOVE-DIR pos_5_6 pos_4_1 act_teleport)
	(MOVE-DIR pos_5_6 pos_4_7 act_teleport)
	(MOVE-DIR pos_5_6 pos_4_8 act_teleport)
	(MOVE-DIR pos_5_6 pos_5_1 act_teleport)
	(MOVE-DIR pos_5_6 pos_5_2 act_teleport)
	(MOVE-DIR pos_5_6 pos_5_3 act_teleport)
	(MOVE-DIR pos_5_6 pos_5_8 act_teleport)
	(MOVE-DIR pos_5_6 pos_6_6 act_teleport)
	(MOVE-DIR pos_5_6 pos_6_7 act_teleport)
	(MOVE-DIR pos_5_6 pos_6_8 act_teleport)
	(MOVE-DIR pos_5_6 pos_7_0 act_teleport)
	(MOVE-DIR pos_5_6 pos_7_1 act_teleport)
	(MOVE-DIR pos_5_6 pos_7_2 act_teleport)
	(MOVE-DIR pos_5_6 pos_7_3 act_teleport)
	(MOVE-DIR pos_5_6 pos_7_4 act_teleport)
	(MOVE-DIR pos_5_8 pos_4_4 act_teleport)
	(MOVE-DIR pos_5_8 pos_0_0 act_teleport)
	(MOVE-DIR pos_5_8 pos_0_8 act_teleport)
	(MOVE-DIR pos_5_8 pos_0_9 act_teleport)
	(MOVE-DIR pos_5_8 pos_1_2 act_teleport)
	(MOVE-DIR pos_5_8 pos_1_3 act_teleport)
	(MOVE-DIR pos_5_8 pos_1_4 act_teleport)
	(MOVE-DIR pos_5_8 pos_1_5 act_teleport)
	(MOVE-DIR pos_5_8 pos_1_6 act_teleport)
	(MOVE-DIR pos_5_8 pos_1_8 act_teleport)
	(MOVE-DIR pos_5_8 pos_2_1 act_teleport)
	(MOVE-DIR pos_5_8 pos_2_2 act_teleport)
	(MOVE-DIR pos_5_8 pos_2_4 act_teleport)
	(MOVE-DIR pos_5_8 pos_2_6 act_teleport)
	(MOVE-DIR pos_5_8 pos_2_8 act_teleport)
	(MOVE-DIR pos_5_8 pos_2_9 act_teleport)
	(MOVE-DIR pos_5_8 pos_3_1 act_teleport)
	(MOVE-DIR pos_5_8 pos_3_2 act_teleport)
	(MOVE-DIR pos_5_8 pos_3_4 act_teleport)
	(MOVE-DIR pos_5_8 pos_3_6 act_teleport)
	(MOVE-DIR pos_5_8 pos_4_1 act_teleport)
	(MOVE-DIR pos_5_8 pos_4_7 act_teleport)
	(MOVE-DIR pos_5_8 pos_4_8 act_teleport)
	(MOVE-DIR pos_5_8 pos_5_1 act_teleport)
	(MOVE-DIR pos_5_8 pos_5_2 act_teleport)
	(MOVE-DIR pos_5_8 pos_5_3 act_teleport)
	(MOVE-DIR pos_5_8 pos_5_6 act_teleport)
	(MOVE-DIR pos_5_8 pos_6_6 act_teleport)
	(MOVE-DIR pos_5_8 pos_6_7 act_teleport)
	(MOVE-DIR pos_5_8 pos_6_8 act_teleport)
	(MOVE-DIR pos_5_8 pos_7_0 act_teleport)
	(MOVE-DIR pos_5_8 pos_7_1 act_teleport)
	(MOVE-DIR pos_5_8 pos_7_2 act_teleport)
	(MOVE-DIR pos_5_8 pos_7_3 act_teleport)
	(MOVE-DIR pos_5_8 pos_7_4 act_teleport)
	(MOVE-DIR pos_6_6 pos_4_4 act_teleport)
	(MOVE-DIR pos_6_6 pos_0_0 act_teleport)
	(MOVE-DIR pos_6_6 pos_0_8 act_teleport)
	(MOVE-DIR pos_6_6 pos_0_9 act_teleport)
	(MOVE-DIR pos_6_6 pos_1_2 act_teleport)
	(MOVE-DIR pos_6_6 pos_1_3 act_teleport)
	(MOVE-DIR pos_6_6 pos_1_4 act_teleport)
	(MOVE-DIR pos_6_6 pos_1_5 act_teleport)
	(MOVE-DIR pos_6_6 pos_1_6 act_teleport)
	(MOVE-DIR pos_6_6 pos_1_8 act_teleport)
	(MOVE-DIR pos_6_6 pos_2_1 act_teleport)
	(MOVE-DIR pos_6_6 pos_2_2 act_teleport)
	(MOVE-DIR pos_6_6 pos_2_4 act_teleport)
	(MOVE-DIR pos_6_6 pos_2_6 act_teleport)
	(MOVE-DIR pos_6_6 pos_2_8 act_teleport)
	(MOVE-DIR pos_6_6 pos_2_9 act_teleport)
	(MOVE-DIR pos_6_6 pos_3_1 act_teleport)
	(MOVE-DIR pos_6_6 pos_3_2 act_teleport)
	(MOVE-DIR pos_6_6 pos_3_4 act_teleport)
	(MOVE-DIR pos_6_6 pos_3_6 act_teleport)
	(MOVE-DIR pos_6_6 pos_4_1 act_teleport)
	(MOVE-DIR pos_6_6 pos_4_7 act_teleport)
	(MOVE-DIR pos_6_6 pos_4_8 act_teleport)
	(MOVE-DIR pos_6_6 pos_5_1 act_teleport)
	(MOVE-DIR pos_6_6 pos_5_2 act_teleport)
	(MOVE-DIR pos_6_6 pos_5_3 act_teleport)
	(MOVE-DIR pos_6_6 pos_5_6 act_teleport)
	(MOVE-DIR pos_6_6 pos_5_8 act_teleport)
	(MOVE-DIR pos_6_6 pos_6_7 act_teleport)
	(MOVE-DIR pos_6_6 pos_6_8 act_teleport)
	(MOVE-DIR pos_6_6 pos_7_0 act_teleport)
	(MOVE-DIR pos_6_6 pos_7_1 act_teleport)
	(MOVE-DIR pos_6_6 pos_7_2 act_teleport)
	(MOVE-DIR pos_6_6 pos_7_3 act_teleport)
	(MOVE-DIR pos_6_6 pos_7_4 act_teleport)
	(MOVE-DIR pos_6_7 pos_4_4 act_teleport)
	(MOVE-DIR pos_6_7 pos_0_0 act_teleport)
	(MOVE-DIR pos_6_7 pos_0_8 act_teleport)
	(MOVE-DIR pos_6_7 pos_0_9 act_teleport)
	(MOVE-DIR pos_6_7 pos_1_2 act_teleport)
	(MOVE-DIR pos_6_7 pos_1_3 act_teleport)
	(MOVE-DIR pos_6_7 pos_1_4 act_teleport)
	(MOVE-DIR pos_6_7 pos_1_5 act_teleport)
	(MOVE-DIR pos_6_7 pos_1_6 act_teleport)
	(MOVE-DIR pos_6_7 pos_1_8 act_teleport)
	(MOVE-DIR pos_6_7 pos_2_1 act_teleport)
	(MOVE-DIR pos_6_7 pos_2_2 act_teleport)
	(MOVE-DIR pos_6_7 pos_2_4 act_teleport)
	(MOVE-DIR pos_6_7 pos_2_6 act_teleport)
	(MOVE-DIR pos_6_7 pos_2_8 act_teleport)
	(MOVE-DIR pos_6_7 pos_2_9 act_teleport)
	(MOVE-DIR pos_6_7 pos_3_1 act_teleport)
	(MOVE-DIR pos_6_7 pos_3_2 act_teleport)
	(MOVE-DIR pos_6_7 pos_3_4 act_teleport)
	(MOVE-DIR pos_6_7 pos_3_6 act_teleport)
	(MOVE-DIR pos_6_7 pos_4_1 act_teleport)
	(MOVE-DIR pos_6_7 pos_4_7 act_teleport)
	(MOVE-DIR pos_6_7 pos_4_8 act_teleport)
	(MOVE-DIR pos_6_7 pos_5_1 act_teleport)
	(MOVE-DIR pos_6_7 pos_5_2 act_teleport)
	(MOVE-DIR pos_6_7 pos_5_3 act_teleport)
	(MOVE-DIR pos_6_7 pos_5_6 act_teleport)
	(MOVE-DIR pos_6_7 pos_5_8 act_teleport)
	(MOVE-DIR pos_6_7 pos_6_6 act_teleport)
	(MOVE-DIR pos_6_7 pos_6_8 act_teleport)
	(MOVE-DIR pos_6_7 pos_7_0 act_teleport)
	(MOVE-DIR pos_6_7 pos_7_1 act_teleport)
	(MOVE-DIR pos_6_7 pos_7_2 act_teleport)
	(MOVE-DIR pos_6_7 pos_7_3 act_teleport)
	(MOVE-DIR pos_6_7 pos_7_4 act_teleport)
	(MOVE-DIR pos_6_8 pos_4_4 act_teleport)
	(MOVE-DIR pos_6_8 pos_0_0 act_teleport)
	(MOVE-DIR pos_6_8 pos_0_8 act_teleport)
	(MOVE-DIR pos_6_8 pos_0_9 act_teleport)
	(MOVE-DIR pos_6_8 pos_1_2 act_teleport)
	(MOVE-DIR pos_6_8 pos_1_3 act_teleport)
	(MOVE-DIR pos_6_8 pos_1_4 act_teleport)
	(MOVE-DIR pos_6_8 pos_1_5 act_teleport)
	(MOVE-DIR pos_6_8 pos_1_6 act_teleport)
	(MOVE-DIR pos_6_8 pos_1_8 act_teleport)
	(MOVE-DIR pos_6_8 pos_2_1 act_teleport)
	(MOVE-DIR pos_6_8 pos_2_2 act_teleport)
	(MOVE-DIR pos_6_8 pos_2_4 act_teleport)
	(MOVE-DIR pos_6_8 pos_2_6 act_teleport)
	(MOVE-DIR pos_6_8 pos_2_8 act_teleport)
	(MOVE-DIR pos_6_8 pos_2_9 act_teleport)
	(MOVE-DIR pos_6_8 pos_3_1 act_teleport)
	(MOVE-DIR pos_6_8 pos_3_2 act_teleport)
	(MOVE-DIR pos_6_8 pos_3_4 act_teleport)
	(MOVE-DIR pos_6_8 pos_3_6 act_teleport)
	(MOVE-DIR pos_6_8 pos_4_1 act_teleport)
	(MOVE-DIR pos_6_8 pos_4_7 act_teleport)
	(MOVE-DIR pos_6_8 pos_4_8 act_teleport)
	(MOVE-DIR pos_6_8 pos_5_1 act_teleport)
	(MOVE-DIR pos_6_8 pos_5_2 act_teleport)
	(MOVE-DIR pos_6_8 pos_5_3 act_teleport)
	(MOVE-DIR pos_6_8 pos_5_6 act_teleport)
	(MOVE-DIR pos_6_8 pos_5_8 act_teleport)
	(MOVE-DIR pos_6_8 pos_6_6 act_teleport)
	(MOVE-DIR pos_6_8 pos_6_7 act_teleport)
	(MOVE-DIR pos_6_8 pos_7_0 act_teleport)
	(MOVE-DIR pos_6_8 pos_7_1 act_teleport)
	(MOVE-DIR pos_6_8 pos_7_2 act_teleport)
	(MOVE-DIR pos_6_8 pos_7_3 act_teleport)
	(MOVE-DIR pos_6_8 pos_7_4 act_teleport)
	(MOVE-DIR pos_7_0 pos_4_4 act_teleport)
	(MOVE-DIR pos_7_0 pos_0_0 act_teleport)
	(MOVE-DIR pos_7_0 pos_0_8 act_teleport)
	(MOVE-DIR pos_7_0 pos_0_9 act_teleport)
	(MOVE-DIR pos_7_0 pos_1_2 act_teleport)
	(MOVE-DIR pos_7_0 pos_1_3 act_teleport)
	(MOVE-DIR pos_7_0 pos_1_4 act_teleport)
	(MOVE-DIR pos_7_0 pos_1_5 act_teleport)
	(MOVE-DIR pos_7_0 pos_1_6 act_teleport)
	(MOVE-DIR pos_7_0 pos_1_8 act_teleport)
	(MOVE-DIR pos_7_0 pos_2_1 act_teleport)
	(MOVE-DIR pos_7_0 pos_2_2 act_teleport)
	(MOVE-DIR pos_7_0 pos_2_4 act_teleport)
	(MOVE-DIR pos_7_0 pos_2_6 act_teleport)
	(MOVE-DIR pos_7_0 pos_2_8 act_teleport)
	(MOVE-DIR pos_7_0 pos_2_9 act_teleport)
	(MOVE-DIR pos_7_0 pos_3_1 act_teleport)
	(MOVE-DIR pos_7_0 pos_3_2 act_teleport)
	(MOVE-DIR pos_7_0 pos_3_4 act_teleport)
	(MOVE-DIR pos_7_0 pos_3_6 act_teleport)
	(MOVE-DIR pos_7_0 pos_4_1 act_teleport)
	(MOVE-DIR pos_7_0 pos_4_7 act_teleport)
	(MOVE-DIR pos_7_0 pos_4_8 act_teleport)
	(MOVE-DIR pos_7_0 pos_5_1 act_teleport)
	(MOVE-DIR pos_7_0 pos_5_2 act_teleport)
	(MOVE-DIR pos_7_0 pos_5_3 act_teleport)
	(MOVE-DIR pos_7_0 pos_5_6 act_teleport)
	(MOVE-DIR pos_7_0 pos_5_8 act_teleport)
	(MOVE-DIR pos_7_0 pos_6_6 act_teleport)
	(MOVE-DIR pos_7_0 pos_6_7 act_teleport)
	(MOVE-DIR pos_7_0 pos_6_8 act_teleport)
	(MOVE-DIR pos_7_0 pos_7_1 act_teleport)
	(MOVE-DIR pos_7_0 pos_7_2 act_teleport)
	(MOVE-DIR pos_7_0 pos_7_3 act_teleport)
	(MOVE-DIR pos_7_0 pos_7_4 act_teleport)
	(MOVE-DIR pos_7_1 pos_4_4 act_teleport)
	(MOVE-DIR pos_7_1 pos_0_0 act_teleport)
	(MOVE-DIR pos_7_1 pos_0_8 act_teleport)
	(MOVE-DIR pos_7_1 pos_0_9 act_teleport)
	(MOVE-DIR pos_7_1 pos_1_2 act_teleport)
	(MOVE-DIR pos_7_1 pos_1_3 act_teleport)
	(MOVE-DIR pos_7_1 pos_1_4 act_teleport)
	(MOVE-DIR pos_7_1 pos_1_5 act_teleport)
	(MOVE-DIR pos_7_1 pos_1_6 act_teleport)
	(MOVE-DIR pos_7_1 pos_1_8 act_teleport)
	(MOVE-DIR pos_7_1 pos_2_1 act_teleport)
	(MOVE-DIR pos_7_1 pos_2_2 act_teleport)
	(MOVE-DIR pos_7_1 pos_2_4 act_teleport)
	(MOVE-DIR pos_7_1 pos_2_6 act_teleport)
	(MOVE-DIR pos_7_1 pos_2_8 act_teleport)
	(MOVE-DIR pos_7_1 pos_2_9 act_teleport)
	(MOVE-DIR pos_7_1 pos_3_1 act_teleport)
	(MOVE-DIR pos_7_1 pos_3_2 act_teleport)
	(MOVE-DIR pos_7_1 pos_3_4 act_teleport)
	(MOVE-DIR pos_7_1 pos_3_6 act_teleport)
	(MOVE-DIR pos_7_1 pos_4_1 act_teleport)
	(MOVE-DIR pos_7_1 pos_4_7 act_teleport)
	(MOVE-DIR pos_7_1 pos_4_8 act_teleport)
	(MOVE-DIR pos_7_1 pos_5_1 act_teleport)
	(MOVE-DIR pos_7_1 pos_5_2 act_teleport)
	(MOVE-DIR pos_7_1 pos_5_3 act_teleport)
	(MOVE-DIR pos_7_1 pos_5_6 act_teleport)
	(MOVE-DIR pos_7_1 pos_5_8 act_teleport)
	(MOVE-DIR pos_7_1 pos_6_6 act_teleport)
	(MOVE-DIR pos_7_1 pos_6_7 act_teleport)
	(MOVE-DIR pos_7_1 pos_6_8 act_teleport)
	(MOVE-DIR pos_7_1 pos_7_0 act_teleport)
	(MOVE-DIR pos_7_1 pos_7_2 act_teleport)
	(MOVE-DIR pos_7_1 pos_7_3 act_teleport)
	(MOVE-DIR pos_7_1 pos_7_4 act_teleport)
	(MOVE-DIR pos_7_2 pos_4_4 act_teleport)
	(MOVE-DIR pos_7_2 pos_0_0 act_teleport)
	(MOVE-DIR pos_7_2 pos_0_8 act_teleport)
	(MOVE-DIR pos_7_2 pos_0_9 act_teleport)
	(MOVE-DIR pos_7_2 pos_1_2 act_teleport)
	(MOVE-DIR pos_7_2 pos_1_3 act_teleport)
	(MOVE-DIR pos_7_2 pos_1_4 act_teleport)
	(MOVE-DIR pos_7_2 pos_1_5 act_teleport)
	(MOVE-DIR pos_7_2 pos_1_6 act_teleport)
	(MOVE-DIR pos_7_2 pos_1_8 act_teleport)
	(MOVE-DIR pos_7_2 pos_2_1 act_teleport)
	(MOVE-DIR pos_7_2 pos_2_2 act_teleport)
	(MOVE-DIR pos_7_2 pos_2_4 act_teleport)
	(MOVE-DIR pos_7_2 pos_2_6 act_teleport)
	(MOVE-DIR pos_7_2 pos_2_8 act_teleport)
	(MOVE-DIR pos_7_2 pos_2_9 act_teleport)
	(MOVE-DIR pos_7_2 pos_3_1 act_teleport)
	(MOVE-DIR pos_7_2 pos_3_2 act_teleport)
	(MOVE-DIR pos_7_2 pos_3_4 act_teleport)
	(MOVE-DIR pos_7_2 pos_3_6 act_teleport)
	(MOVE-DIR pos_7_2 pos_4_1 act_teleport)
	(MOVE-DIR pos_7_2 pos_4_7 act_teleport)
	(MOVE-DIR pos_7_2 pos_4_8 act_teleport)
	(MOVE-DIR pos_7_2 pos_5_1 act_teleport)
	(MOVE-DIR pos_7_2 pos_5_2 act_teleport)
	(MOVE-DIR pos_7_2 pos_5_3 act_teleport)
	(MOVE-DIR pos_7_2 pos_5_6 act_teleport)
	(MOVE-DIR pos_7_2 pos_5_8 act_teleport)
	(MOVE-DIR pos_7_2 pos_6_6 act_teleport)
	(MOVE-DIR pos_7_2 pos_6_7 act_teleport)
	(MOVE-DIR pos_7_2 pos_6_8 act_teleport)
	(MOVE-DIR pos_7_2 pos_7_0 act_teleport)
	(MOVE-DIR pos_7_2 pos_7_1 act_teleport)
	(MOVE-DIR pos_7_2 pos_7_3 act_teleport)
	(MOVE-DIR pos_7_2 pos_7_4 act_teleport)
	(MOVE-DIR pos_7_3 pos_4_4 act_teleport)
	(MOVE-DIR pos_7_3 pos_0_0 act_teleport)
	(MOVE-DIR pos_7_3 pos_0_8 act_teleport)
	(MOVE-DIR pos_7_3 pos_0_9 act_teleport)
	(MOVE-DIR pos_7_3 pos_1_2 act_teleport)
	(MOVE-DIR pos_7_3 pos_1_3 act_teleport)
	(MOVE-DIR pos_7_3 pos_1_4 act_teleport)
	(MOVE-DIR pos_7_3 pos_1_5 act_teleport)
	(MOVE-DIR pos_7_3 pos_1_6 act_teleport)
	(MOVE-DIR pos_7_3 pos_1_8 act_teleport)
	(MOVE-DIR pos_7_3 pos_2_1 act_teleport)
	(MOVE-DIR pos_7_3 pos_2_2 act_teleport)
	(MOVE-DIR pos_7_3 pos_2_4 act_teleport)
	(MOVE-DIR pos_7_3 pos_2_6 act_teleport)
	(MOVE-DIR pos_7_3 pos_2_8 act_teleport)
	(MOVE-DIR pos_7_3 pos_2_9 act_teleport)
	(MOVE-DIR pos_7_3 pos_3_1 act_teleport)
	(MOVE-DIR pos_7_3 pos_3_2 act_teleport)
	(MOVE-DIR pos_7_3 pos_3_4 act_teleport)
	(MOVE-DIR pos_7_3 pos_3_6 act_teleport)
	(MOVE-DIR pos_7_3 pos_4_1 act_teleport)
	(MOVE-DIR pos_7_3 pos_4_7 act_teleport)
	(MOVE-DIR pos_7_3 pos_4_8 act_teleport)
	(MOVE-DIR pos_7_3 pos_5_1 act_teleport)
	(MOVE-DIR pos_7_3 pos_5_2 act_teleport)
	(MOVE-DIR pos_7_3 pos_5_3 act_teleport)
	(MOVE-DIR pos_7_3 pos_5_6 act_teleport)
	(MOVE-DIR pos_7_3 pos_5_8 act_teleport)
	(MOVE-DIR pos_7_3 pos_6_6 act_teleport)
	(MOVE-DIR pos_7_3 pos_6_7 act_teleport)
	(MOVE-DIR pos_7_3 pos_6_8 act_teleport)
	(MOVE-DIR pos_7_3 pos_7_0 act_teleport)
	(MOVE-DIR pos_7_3 pos_7_1 act_teleport)
	(MOVE-DIR pos_7_3 pos_7_2 act_teleport)
	(MOVE-DIR pos_7_3 pos_7_4 act_teleport)
	(MOVE-DIR pos_7_4 pos_4_4 act_teleport)
	(MOVE-DIR pos_7_4 pos_0_0 act_teleport)
	(MOVE-DIR pos_7_4 pos_0_8 act_teleport)
	(MOVE-DIR pos_7_4 pos_0_9 act_teleport)
	(MOVE-DIR pos_7_4 pos_1_2 act_teleport)
	(MOVE-DIR pos_7_4 pos_1_3 act_teleport)
	(MOVE-DIR pos_7_4 pos_1_4 act_teleport)
	(MOVE-DIR pos_7_4 pos_1_5 act_teleport)
	(MOVE-DIR pos_7_4 pos_1_6 act_teleport)
	(MOVE-DIR pos_7_4 pos_1_8 act_teleport)
	(MOVE-DIR pos_7_4 pos_2_1 act_teleport)
	(MOVE-DIR pos_7_4 pos_2_2 act_teleport)
	(MOVE-DIR pos_7_4 pos_2_4 act_teleport)
	(MOVE-DIR pos_7_4 pos_2_6 act_teleport)
	(MOVE-DIR pos_7_4 pos_2_8 act_teleport)
	(MOVE-DIR pos_7_4 pos_2_9 act_teleport)
	(MOVE-DIR pos_7_4 pos_3_1 act_teleport)
	(MOVE-DIR pos_7_4 pos_3_2 act_teleport)
	(MOVE-DIR pos_7_4 pos_3_4 act_teleport)
	(MOVE-DIR pos_7_4 pos_3_6 act_teleport)
	(MOVE-DIR pos_7_4 pos_4_1 act_teleport)
	(MOVE-DIR pos_7_4 pos_4_7 act_teleport)
	(MOVE-DIR pos_7_4 pos_4_8 act_teleport)
	(MOVE-DIR pos_7_4 pos_5_1 act_teleport)
	(MOVE-DIR pos_7_4 pos_5_2 act_teleport)
	(MOVE-DIR pos_7_4 pos_5_3 act_teleport)
	(MOVE-DIR pos_7_4 pos_5_6 act_teleport)
	(MOVE-DIR pos_7_4 pos_5_8 act_teleport)
	(MOVE-DIR pos_7_4 pos_6_6 act_teleport)
	(MOVE-DIR pos_7_4 pos_6_7 act_teleport)
	(MOVE-DIR pos_7_4 pos_6_8 act_teleport)
	(MOVE-DIR pos_7_4 pos_7_0 act_teleport)
	(MOVE-DIR pos_7_4 pos_7_1 act_teleport)
	(MOVE-DIR pos_7_4 pos_7_2 act_teleport)
	(MOVE-DIR pos_7_4 pos_7_3 act_teleport)
	(MOVE-DIR pos_4_4 pos_3_4 act_down)
	(MOVE-DIR pos_4_4 pos_4_3 act_left)
	(MOVE-DIR pos_4_4 pos_4_5 act_right)
	(MOVE-DIR pos_0_8 pos_1_8 act_up)
	(MOVE-DIR pos_0_8 pos_0_9 act_right)
	(MOVE-DIR pos_0_9 pos_0_8 act_left)
	(MOVE-DIR pos_1_2 pos_2_2 act_up)
	(MOVE-DIR pos_1_2 pos_1_3 act_right)
	(MOVE-DIR pos_1_3 pos_2_3 act_up)
	(MOVE-DIR pos_1_3 pos_1_2 act_left)
	(MOVE-DIR pos_1_3 pos_1_4 act_right)
	(MOVE-DIR pos_1_4 pos_2_4 act_up)
	(MOVE-DIR pos_1_4 pos_1_3 act_left)
	(MOVE-DIR pos_1_4 pos_1_5 act_right)
	(MOVE-DIR pos_1_5 pos_2_5 act_up)
	(MOVE-DIR pos_1_5 pos_1_4 act_left)
	(MOVE-DIR pos_1_5 pos_1_6 act_right)
	(MOVE-DIR pos_1_6 pos_2_6 act_up)
	(MOVE-DIR pos_1_6 pos_1_5 act_left)
	(MOVE-DIR pos_1_8 pos_2_8 act_up)
	(MOVE-DIR pos_1_8 pos_0_8 act_down)
	(MOVE-DIR pos_2_1 pos_3_1 act_up)
	(MOVE-DIR pos_2_1 pos_2_2 act_right)
	(MOVE-DIR pos_2_2 pos_3_2 act_up)
	(MOVE-DIR pos_2_2 pos_1_2 act_down)
	(MOVE-DIR pos_2_2 pos_2_1 act_left)
	(MOVE-DIR pos_2_2 pos_2_3 act_right)
	(MOVE-DIR pos_2_3 pos_3_3 act_up)
	(MOVE-DIR pos_2_3 pos_1_3 act_down)
	(MOVE-DIR pos_2_3 pos_2_2 act_left)
	(MOVE-DIR pos_2_3 pos_2_4 act_right)
	(MOVE-DIR pos_2_4 pos_3_4 act_up)
	(MOVE-DIR pos_2_4 pos_1_4 act_down)
	(MOVE-DIR pos_2_4 pos_2_3 act_left)
	(MOVE-DIR pos_2_4 pos_2_5 act_right)
	(MOVE-DIR pos_2_5 pos_1_5 act_down)
	(MOVE-DIR pos_2_5 pos_2_4 act_left)
	(MOVE-DIR pos_2_5 pos_2_6 act_right)
	(MOVE-DIR pos_2_6 pos_3_6 act_up)
	(MOVE-DIR pos_2_6 pos_1_6 act_down)
	(MOVE-DIR pos_2_6 pos_2_5 act_left)
	(MOVE-DIR pos_2_8 pos_1_8 act_down)
	(MOVE-DIR pos_2_8 pos_2_9 act_right)
	(MOVE-DIR pos_2_9 pos_2_8 act_left)
	(MOVE-DIR pos_3_1 pos_4_1 act_up)
	(MOVE-DIR pos_3_1 pos_2_1 act_down)
	(MOVE-DIR pos_3_1 pos_3_2 act_right)
	(MOVE-DIR pos_3_2 pos_2_2 act_down)
	(MOVE-DIR pos_3_2 pos_3_1 act_left)
	(MOVE-DIR pos_3_2 pos_3_3 act_right)
	(MOVE-DIR pos_3_3 pos_4_3 act_up)
	(MOVE-DIR pos_3_3 pos_2_3 act_down)
	(MOVE-DIR pos_3_3 pos_3_2 act_left)
	(MOVE-DIR pos_3_3 pos_3_4 act_right)
	(MOVE-DIR pos_3_4 pos_4_4 act_up)
	(MOVE-DIR pos_3_4 pos_2_4 act_down)
	(MOVE-DIR pos_3_4 pos_3_3 act_left)
	(MOVE-DIR pos_3_6 pos_4_6 act_up)
	(MOVE-DIR pos_3_6 pos_2_6 act_down)
	(MOVE-DIR pos_4_1 pos_5_1 act_up)
	(MOVE-DIR pos_4_1 pos_3_1 act_down)
	(MOVE-DIR pos_4_3 pos_5_3 act_up)
	(MOVE-DIR pos_4_3 pos_3_3 act_down)
	(MOVE-DIR pos_4_3 pos_4_4 act_right)
	(MOVE-DIR pos_4_5 pos_4_4 act_left)
	(MOVE-DIR pos_4_5 pos_4_6 act_right)
	(MOVE-DIR pos_4_6 pos_5_6 act_up)
	(MOVE-DIR pos_4_6 pos_3_6 act_down)
	(MOVE-DIR pos_4_6 pos_4_5 act_left)
	(MOVE-DIR pos_4_6 pos_4_7 act_right)
	(MOVE-DIR pos_4_7 pos_4_6 act_left)
	(MOVE-DIR pos_4_7 pos_4_8 act_right)
	(MOVE-DIR pos_4_8 pos_5_8 act_up)
	(MOVE-DIR pos_4_8 pos_4_7 act_left)
	(MOVE-DIR pos_5_1 pos_4_1 act_down)
	(MOVE-DIR pos_5_1 pos_5_2 act_right)
	(MOVE-DIR pos_5_2 pos_5_1 act_left)
	(MOVE-DIR pos_5_2 pos_5_3 act_right)
	(MOVE-DIR pos_5_3 pos_4_3 act_down)
	(MOVE-DIR pos_5_3 pos_5_2 act_left)
	(MOVE-DIR pos_5_6 pos_6_6 act_up)
	(MOVE-DIR pos_5_6 pos_4_6 act_down)
	(MOVE-DIR pos_5_8 pos_6_8 act_up)
	(MOVE-DIR pos_5_8 pos_4_8 act_down)
	(MOVE-DIR pos_6_6 pos_5_6 act_down)
	(MOVE-DIR pos_6_6 pos_6_7 act_right)
	(MOVE-DIR pos_6_7 pos_6_6 act_left)
	(MOVE-DIR pos_6_7 pos_6_8 act_right)
	(MOVE-DIR pos_6_8 pos_5_8 act_down)
	(MOVE-DIR pos_6_8 pos_6_7 act_left)
	(MOVE-DIR pos_7_0 pos_7_1 act_right)
	(MOVE-DIR pos_7_1 pos_7_0 act_left)
	(MOVE-DIR pos_7_1 pos_7_2 act_right)
	(MOVE-DIR pos_7_2 pos_7_1 act_left)
	(MOVE-DIR pos_7_2 pos_7_3 act_right)
	(MOVE-DIR pos_7_3 pos_7_2 act_left)
	(MOVE-DIR pos_7_3 pos_7_4 act_right)
	(MOVE-DIR pos_7_4 pos_7_3 act_left)
)
(:goal (and
	(at_goal box_0)
	(at_goal box_1)
	(at_goal box_2)
	(at_goal box_3)
	(at_goal box_4)
	(at_goal box_5)
)))